/*
winamp remote control suite �Patrick Michael Martin 2000, 2001, 2002

Copyright (C) 2000,2001,2002  Patrick M. Martin

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

Patrick M. Martin may be reached by email at patrickmmartin@gmail.com.
*/

#include "winampinterface.h"    // header file generated by MIDL compiler

extern void * winamp_IfHandle;

// hard-coded for tcpip
static unsigned char * pszProtocolSequence = (unsigned char *) "ncacn_ip_tcp";
// global string binding information
static unsigned char * StringBinding = 0;

// this unbinds to the interface after the RPC call
void __stdcall UnBind(void)
{
    RpcStringFree(&StringBinding);
    StringBinding = NULL;
    RpcBindingFree(&winamp_IfHandle);
}

// this binds to the interface , and assigns to the interface handle
void __stdcall Bind(char * NetworkAddress, char * EndPoint)
{
  // avoid leaking handles ?
  if (StringBinding)
    UnBind();

  RpcStringBindingCompose(NULL,
                          pszProtocolSequence,
                          (unsigned char *) NetworkAddress,
                          (unsigned char *)EndPoint,
                          NULL,
                          &StringBinding);
  RpcBindingFromStringBinding(StringBinding, &winamp_IfHandle);

}


