// winamp remote control suite ©Patrick Michael Martin 2000
//
// PlayListF.cpp
//
// form displaying and allowing editing of playlist
//

#include <vcl.h>
#pragma hdrstop

#include "PlaylistProF.h"
#include "waint.h"
#include "MainProF.h"
#include "RPCFuncsU.h"

//---------------------------------------------------------------------------
#pragma package(smart_init)
#pragma resource "*.dfm"

// turn off warnings
#include "winampinterface.h"    // header file generated by MIDL compiler


const int Offset = 4;

TfrmPlaylist *frmPlaylist;
//---------------------------------------------------------------------------
__fastcall TfrmPlaylist::TfrmPlaylist(TComponent* Owner)
    : TForm(Owner)
{
}
//---------------------------------------------------------------------------

void __fastcall TfrmPlaylist::SongsRefresh(TObject *Sender)
{

  try
  {
    try
    {

      Screen->Cursor = crAppStart;
      lstSongs->Items->BeginUpdate();
      lastlength = IntegerResult(IdentChars, IPC_GETLISTLENGTH, 0);
      lastindex = currentpos;
      currentpos = IntegerResult(IdentChars, IPC_GETLISTPOS, 0);

      lstSongs->Items->Clear();

      void * buf = NULL;
      int bufsize = 0;

      GetList(IdentChars, &buf, bufsize, IPC_GETPLAYLISTTITLE);

      if (bufsize)
        lstSongs->Items->Text = (char *) buf;

      if (buf)
        delete buf;

    }
    catch( ERPCException &E)
    {
      lstSongs->Items->Text = "<list unobtainable: " + E.Message + ">";
    }


  }
  __finally
  {
    Screen->Cursor = crDefault;
    frmMain->sbMain->Panels->Items[0]->Text = "idle";
    lstSongs->Items->EndUpdate();
  }

}
//---------------------------------------------------------------------------

void __fastcall TfrmPlaylist::lstSongsDblClick(TObject *Sender)
{
  IntegerResult(IdentChars, IPC_SETPLAYLISTPOS, lstSongs->ItemIndex);
  ExecuteMessage(IdentChars, WINAMP_PLAYENTRY);

}
//---------------------------------------------------------------------------


void __fastcall TfrmPlaylist::mnuSortClick(TObject *Sender)
{
// these *STILL* don't bleeding work!
  if (Sender == mnuSort)
  {
    IntegerResult(IdentChars, IDC_SORT_FILETITLE, 0);
  }
  if (Sender == mnuSortFile)
  {
    IntegerResult(IdentChars, IDC_SORT_FILENAME, 0);
  }
  if (Sender == mnuSortFileEntire)
  {
    IntegerResult(IdentChars, IDC_SORT_ENTIREFILENAME, 0);
  }

  SongsRefresh(this);
}
//---------------------------------------------------------------------------

void __fastcall TfrmPlaylist::FormCreate(TObject *Sender)
{

  lstSongs->ItemHeight = this->Canvas->TextHeight('W');
//  SongsRefresh(this);

}
//---------------------------------------------------------------------------

void __fastcall TfrmPlaylist::DeleteSelected(void)
{
int i;

  Screen->Cursor = crAppStart;
  TStringList * StringList = new TStringList;
  try
  {
  /* rather wasteful, as we have to get all the undeleted items and resend them to winamp*/

    void * buf = NULL;
    int bufsize = 0;

    GetList(IdentChars, &buf, bufsize, IPC_GETPLAYLISTFILE);

    if (bufsize)
      StringList->Text = (char *) buf;

    if (buf)
      delete buf;

    int playingpos = currentpos;

    for (i = lstSongs->Items->Count - 1 ; i >= 0 ; i--)
    {
      if (lstSongs->Selected[i])
      {
        StringList->Delete(i);
         if (i < playingpos)
            playingpos--;
      }
    } // for

    // delete current
    IntegerResult(IdentChars, IPC_DELETE, 0);

    // add remaining
    AddFiles(StringList);
    // reset position

    IntegerResult(IdentChars, IPC_SETPLAYLISTPOS, playingpos);

    SongsRefresh(this);
  }
  __finally
  {
    delete StringList;
    Screen->Cursor = crDefault;
  }

}

//---------------------------------------------------------------------------


void __fastcall TfrmPlaylist::lstSongsDrawItem(TWinControl *Control,
      int Index, TRect &Rect, TOwnerDrawState State)
{
  TCanvas *pCanvas = ((TListBox *)Control)->Canvas;
  pCanvas->FillRect(Rect);

  if (Index == currentpos)
  {
    pCanvas->Font->Color = clRed;
  }
  pCanvas->TextOut(Rect.Left + Offset, Rect.Top, ((TListBox *)Control)->Items->Strings[Index]);
  pCanvas->Font->Color = clWindowText;

}
//---------------------------------------------------------------------------

void __fastcall TfrmPlaylist::DropFiles(TMessage& Msg)
{
  char CFileName[MAX_PATH];
  int len, i;
  TStringList * Files = new TStringList;
  void * hDrop = (void *) Msg.WParam;
  int NewPos;

  TPoint DropPoint;

  int DropIndex;
  DragQueryPoint(hDrop, &DropPoint);

  // this returns -1 if there was a hit item
  DropIndex = lstSongs->ItemAtPos(DropPoint, true);

  // get the top of the list
  if (DropIndex > -1)
    GetFilenames(0, DropIndex, Files);
  else
    GetFilenames(0, lstSongs->Items->Count, Files);

  try
  {
    len = DragQueryFile((void *) hDrop, 0xFFFFFFFF, NULL, 0);
    for (i = 0 ; i < len ; i++){
      if (DragQueryFile((void *) hDrop, i, CFileName, MAX_PATH) > 0){
        Files->Add(CFileName);
        }
      }

  // get the rest of the list;
  if (DropIndex > -1)
    GetFilenames(DropIndex, lstSongs->Items->Count, Files);

    // delete
    IntegerResult(IdentChars, IPC_DELETE, 0);

    AddFiles(Files);
  // reset position here

  NewPos = Files->IndexOfObject((TObject *) true);
  IntegerResult(IdentChars, IPC_SETPLAYLISTPOS, NewPos);


    SongsRefresh(this);

    }
  __finally
  {
    DragFinish((void *) Msg.WParam);
    delete Files;
  }

}

//---------------------------------------------------------------------------

void __fastcall TfrmPlaylist::AddFiles(TStringList * Files)
{

  Screen->Cursor = crHourGlass;
  try
  {
    SendList(IdentChars, Files->Text.c_str(), Files->Text.Length() + 1, IPC_PLAYFILE);
  }
  __finally
  {
    Screen->Cursor = crDefault;
  }


}

//---------------------------------------------------------------------------

void __fastcall TfrmPlaylist::SongIndexUpdate(TObject *Sender)
{

  char title[RET_STR_SIZE];
  // needed to ensure we can see the currently playing track
  try
  {
    lstSongs->Items->BeginUpdate();
     strcpy(title, IdentChars);
     // update the current title, at least
     StringResult(title, IPC_GETPLAYLISTTITLE, currentpos);

     if ((lstSongs->Items->Count - 1) > currentpos)
     {
       bool Selected = lstSongs->Selected[currentpos];
       lstSongs->Items->Strings[currentpos] = title;
       lstSongs->Selected[currentpos] =  Selected;
     }

    /* much neater... */
    lstSongs->TopIndex = currentpos - 2;
    lstSongs->Refresh();

  }
  __finally
  {
    lstSongs->Items->EndUpdate();
  }
}

//---------------------------------------------------------------------------

void __fastcall TfrmPlaylist::FormClose(TObject *Sender,
      TCloseAction &Action)
{
  frmMain->ViewPlaylist->Execute();
}
//---------------------------------------------------------------------------


void __fastcall TfrmPlaylist::GetFilenames(int Start, int Stop, TStringList * StringList)
{
int i;

char filename[RET_STR_SIZE];
char saveident[RET_STR_SIZE];


int SongS = IntegerResult (IdentChars, IPC_GETOUTPUTTIME, 1);

  strcpy(saveident, IdentChars);

  for (i = Start ; i < Stop; i++)
  {
    strcpy(filename, saveident);
    StringResult(filename, IPC_GETPLAYLISTFILE, i);
    StringList->AddObject(filename, (TObject*) (SongS));
  }

}


//---------------------------------------------------------------------------

void __fastcall TfrmPlaylist::lstSongsDragOver(TObject *Sender,
      TObject *Source, int X, int Y, TDragState State, bool &Accept)
{
  Accept = true;
}
//---------------------------------------------------------------------------

void __fastcall TfrmPlaylist::lstSongsDragDrop(TObject *Sender,
      TObject *Source, int X, int Y)
{
int i;

char filename[RET_STR_SIZE];
char saveident[RET_STR_SIZE];
bool CurrentSong;
int NewPos;

  // want to know if exceed the list length
  int DropIndex = lstSongs->ItemAtPos(TPoint(X, Y), false);


  TStringList * TopList = new TStringList;
  TStringList * MiddleList = new TStringList;
  TStringList * BottomList = new TStringList;
  try
  {
  /* rather wasteful, as we have to get all the undeleted items and resend them to winamp*/

    // cache this
  strcpy(saveident, IdentChars);

    for (i = 0 ; i < lstSongs->Items->Count; i++)
    {
      strcpy(filename, saveident);
      StringResult(filename, IPC_GETPLAYLISTFILE, i);
      CurrentSong = i == currentpos;

      if (lstSongs->Selected[i])
      {
        MiddleList->AddObject(filename, (TObject *) CurrentSong);
      }
      else if (i < DropIndex)
      {
        TopList->AddObject(filename, (TObject *) CurrentSong);
      }
      else
      {
        BottomList->AddObject(filename, (TObject *) CurrentSong);
      }
    } // for

    // delete
    IntegerResult(IdentChars, IPC_DELETE, 0);

    // rebuild list
    TopList->AddStrings(MiddleList);
    TopList->AddStrings(BottomList);
  // reset position

  AddFiles(TopList);

  NewPos = TopList->IndexOfObject((TObject *) true);
  IntegerResult(IdentChars, IPC_SETPLAYLISTPOS, NewPos);

  SongsRefresh(this);
  }
  __finally
  {
    delete BottomList;
    delete MiddleList;
    delete TopList;
  }
}
//---------------------------------------------------------------------------


void __fastcall TfrmPlaylist::FormStartDock(TObject *Sender,
      TDragDockObject *&DragObject)
{
  frmMain->StartDock(Sender, DragObject);

}
//---------------------------------------------------------------------------

void __fastcall TfrmPlaylist::FormShow(TObject *Sender)
{
  // need to re-assert this
  DragAcceptFiles(lstSongs->Handle, true);

}
//---------------------------------------------------------------------------

void __fastcall TfrmPlaylist::FormEndDock(TObject *Sender, TObject *Target,
      int X, int Y)
{
  frmMain->EndDock(Sender, Target, X, Y);
}
//---------------------------------------------------------------------------


void __fastcall TfrmPlaylist::lstSongsMouseMove(TObject *Sender,
      TShiftState Shift, int X, int Y)
{

  int Index = lstSongs->ItemAtPos(TPoint(X, Y), true);

  if (Index > -1)
  {
    if (lstSongs->Canvas->TextWidth(lstSongs->Items->Strings[Index]) > lstSongs->ClientWidth - Offset)
    {
      lstSongs->Hint = lstSongs->Items->Strings[Index];
    }
    else
      lstSongs->Hint = "";

  }
  else
  {
    lstSongs->Hint = "Playlist view -drag files to the desired location";
  }

}
//---------------------------------------------------------------------------

void __fastcall TfrmPlaylist::mnuPlayClick(TObject *Sender)
{

  if (BelowIndex > -1)
  {
    lstSongs->ItemIndex = BelowIndex;
    lstSongsDblClick(this);
  }

}
//---------------------------------------------------------------------------


void __fastcall TfrmPlaylist::pmnuSongsPopup(TObject *Sender)
{

  BelowIndex = lstSongs->ItemAtPos(lstSongs->ScreenToClient(Mouse->CursorPos), true);
  mnuPlay->Enabled = (BelowIndex > -1);
  if (BelowIndex > -1)
    mnuPlay->Caption = lstSongs->Items->Strings[BelowIndex];
  else
    mnuPlay->Caption = "Play";


}
//---------------------------------------------------------------------------

void __fastcall TfrmPlaylist::lstSongsKeyDown(TObject *Sender, WORD &Key,
      TShiftState Shift)
{

  switch (Key)
  {
    case VK_DELETE:
      DeleteSelected(); break;
    case 13 :
      lstSongsDblClick(this);
  }

}
//---------------------------------------------------------------------------

void __fastcall TfrmPlaylist::StatsUpdate(void)
{

//
}





