/*
winamp remote control suite �Patrick Michael Martin 2000, 2001, 2002

Copyright (C) 2000,2001,2002  Patrick M. Martin

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

Patrick M. Martin may be reached by email at patrickmmartin@gmail.com.
*/

#pragma hdrstop

#include "RFC1060U.h"

//---------------------------------------------------------------------------
#pragma package(smart_init)

  porttype RFC1060ports[] =
  {

    {"r", 0, "Reserved"}, 
    {"tcpmux", 1, "TCP Port Service Multiplexer"}, 
    {"compressnet", 2, "Management Utility"}, 
    {"compressnet", 3, "Compression Process"}, 
    {"rje", 5, "Remote Job Entry"}, 
    {"echo", 7, "Echo"}, 
    {"discard", 9, "Discard"}, 
    {"systat", 11, "Active Users"}, 
    {"daytime", 13, "Daytime"}, 
    {"qotd", 17, "Quote of the Day"}, 
    {"msp", 18, "Message Send Protocol"}, 
    {"chargen", 19, "Character Generator"}, 
    {"ftp-data", 20, "File Transfer [Default Data]"}, 
    {"ftp", 21, "File Transfer [Control]"}, 
    {"ssh", 22, "SSH Remote Login Protocol"}, 
    {"telnet", 23, "Telnet"}, 
    {"", 24, "any private mail system"},
    {"smtp", 25, "Simple Mail Transfer"},
    {"nsw-fe", 27, "NSW User System FE"}, 
    {"msg-icp", 29, "MSG ICP"}, 
    {"msg-auth", 31, "MSG Authentication"}, 
    {"dsp", 33, "Display Support Protocol"}, 
    {"", 35, "any private printer server"}, 
    {"time", 37, "Time"}, 
    {"rap", 38, "Route Access Protocol"}, 
    {"rlp", 39, "Resource Location Protocol"}, 
    {"graphics", 41, "Graphics"}, 
    {"name", 42, "Host Name Server"}, 
    {"nameserver", 42, "Host Name Server"}, 
    {"nicname", 43, "Who Is"}, 
    {"mpm-flags", 44, "MPM FLAGS Protocol"}, 
    {"mpm", 45, "Message Processing Module [recv]"}, 
    {"mpm-snd", 46, "MPM [default send]"}, 
    {"ni-ftp", 47, "NI FTP"}, 
    {"auditd", 48, "Digital Audit Daemon"}, 
    {"tacacs", 49, "Login Host Protocol (TACACS)"}, 
    {"re-mail-ck", 50, "Remote Mail Checking Protocol"}, 
    {"la-maint", 51, "IMP Logical Address Maintenance"}, 
    {"xns-time", 52, "XNS Time Protocol"}, 
    {"domain", 53, "Domain Name Server"}, 
    {"xns-ch", 54, "XNS Clearinghouse"}, 
    {"isi-gl", 55, "ISI Graphics Language"}, 
    {"xns-auth", 56, "XNS Authentication"}, 
    {"", 57, "any private terminal access"},
    {"xns-mail", 58, "XNS Mail"}, 
    {"", 59, "any private file service"},
    {"ni-mail", 61, "NI MAIL"}, 
    {"acas", 62, "ACA Services"}, 
    {"whois++", 63, "whois++"}, 
    {"covia", 64, "Communications Integrator (CI)"}, 
    {"tacacs-ds", 65, "TACACS-Database Service"}, 
    {"sql*net", 66, "Oracle SQL*NET"}, 
    {"bootps", 67, "Bootstrap Protocol Server"}, 
    {"bootpc", 68, "Bootstrap Protocol Client"}, 
    {"tftp", 69, "Trivial File Transfer"}, 
    {"gopher", 70, "Gopher"}, 
    {"netrjs-1", 71, "Remote Job Service"}, 
    {"netrjs-2", 72, "Remote Job Service"}, 
    {"netrjs-3", 73, "Remote Job Service"}, 
    {"netrjs-4", 74, "Remote Job Service"}, 
    {"", 75, "any private dial out service"}, 
    {"deos", 76, "Distributed External Object Store"}, 
    {"", 77, "any private RJE service"}, 
    {"vettcp", 78, "vettcp"}, 
    {"finger", 79, "Finger"}, 
    {"http", 80, "World Wide Web HTTP"}, 
    {"www", 80, "World Wide Web HTTP"}, 
    {"www-http", 80, "World Wide Web HTTP"}, 
    {"hosts2-ns", 81, "HOSTS2 Name Server"}, 
    {"xfer", 82, "XFER Utility"}, 
    {"mit-ml-dev", 83, "MIT ML Device"},
    {"ctf", 84, "Common Trace Facility"}, 
    {"mit-ml-dev", 85, "MIT ML Device"}, 
    {"mfcobol", 86, "Micro Focus Cobol"},
    {"", 87, "any private terminal link"}, 
    {"kerberos", 88, "Kerberos"}, 
    {"su-mit-tg", 89, "SU/MIT Telnet Gateway"}, 
    {"dnsix", 90, "DNSIX Securit Attribute Token Map"}, 
    {"mit-dov", 91, "MIT Dover Spooler"}, 
    {"npp", 92, "Network Printing Protocol"}, 
    {"dcp", 93, "Device Control Protocol"}, 
    {"objcall", 94, "Tivoli Object Dispatcher"}, 
    {"supdup", 95, "SUPDUP"}, 
    {"dixie", 96, "DIXIE Protocol Specification"}, 
    {"swift-rvf", 97, "Swift Remote Virtural File Protocol"}, 
    {"tacnews", 98, "TAC News"}, 
    {"metagram", 99, "Metagram Relay"}, 
    {"newacct", 100, "[unauthorized use]"}, 
    {"hostname", 101, "NIC Host Name Server"}, 
    {"iso-tsap", 102, "ISO-TSAP Class 0"}, 
    {"gppitnp", 103, "Genesis Point-to-Point Trans Net"}, 
    {"acr-nema", 104, "ACR-NEMA Digital Imag. & Comm. 300"}, 
    {"cso", 105, "CCSO name server protocol"}, 
    {"cso", 105, "CCSO name server protocol"}, 
    {"csnet-ns", 105, "Mailbox Name Nameserver"}, 
    {"3com-tsmux", 106, " 3COM-TSMUX"}, 
    {"rtelnet", 107, "Remote Telnet Service"}, 
    {"snagas", 108, "SNA Gateway Access Server"},
    {"pop2", 109, "Post Office Protocol - Version 2"}, 
    {"pop3", 110, "Post Office Protocol - Version 3"}, 
    {"sunrpc", 111, "SUN Remote Procedure Call"}, 
    {"mcidas", 112, "McIDAS Data Transmission Protocol"},
    {"ident", 113, "ident"}, 
    {"auth", 113, "Authentication Service"}, 
    {"audionews", 114, "Audio News Multicast"}, 
    {"sftp", 115, "Simple File Transfer Protocol"}, 
    {"ansanotify", 116, "ANSA REX Notify"}, 
    {"uucp-path", 117, "UUCP Path Service"}, 
    {"sqlserv", 118, "SQL Services"}, 
    {"nntp", 119, "Network News Transfer Protocol"}, 
    {"cfdptkt", 120, "CFDPTKT"}, 
    {"erpc", 121, "Encore Expedited Remote Pro.Call"}, 
    {"smakynet", 122, "SMAKYNET"}, 
    {"ntp", 123, "Network Time Protocol"}, 
    {"ansatrader", 124, "ANSA REX Trader"}, 
    {"locus-map", 125, "Locus PC-Interface Net Map Ser"}, 
    {"unitary", 126, "Unisys Unitary Login"}, 
    {"locus-con", 127, "Locus PC-Interface Conn Server"}, 
    {"gss-xlicen", 128, "GSS X License Verification"}, 
    {"pwdgen", 129, "Password Generator Protocol"}, 
    {"cisco-fna", 130, "cisco FNATIVE"}, 
    {"cisco-tna", 131, "cisco TNATIVE"}, 
    {"cisco-sys", 132, "cisco SYSMAINT"}, 
    {"statsrv", 133, "Statistics Service"}, 
    {"ingres-net", 134, "INGRES-NET Service"},
    {"epmap", 135, "DCE endpoint resolution"}, 
    {"profile", 136, "PROFILE Naming System"}, 
    {"netbios-ns", 137, "NETBIOS Name Service"}, 
    {"netbios-dgm", 138, "NETBIOS Datagram Service"}, 
    {"netbios-ssn", 139, "NETBIOS Session Service"},
    {"emfis-data", 140, "EMFIS Data Service"}, 
    {"emfis-cntl", 141, "EMFIS Control Service"}, 
    {"bl-idm", 142, "Britton-Lee IDM"}, 
    {"imap", 143, "Internet Message Access Protocol"}, 
    {"news", 144, "NewS"}, 
    {"uaac", 145, "UAAC Protocol"}, 
    {"iso-tp0", 146, "ISO-IP0"}, 
    {"iso-ip", 147, "ISO-IP"}, 
    {"jargon", 148, "Jargon"}, 
    {"aed-512", 149, "AED 512 Emulation Service"}, 
    {"sql-net", 150, "SQL-NET"}, 
    {"hems", 151, "HEMS"}, 
    {"bftp", 152, "Background File Transfer Program"}, 
    {"sgmp", 153, "SGMP"}, 
    {"netsc-prod", 154, "NETSC"}, 
    {"netsc-dev", 155, "NETSC"}, 
    {"sqlsrv", 156, "SQL Service"}, 
    {"knet-cmp", 157, "KNET/VM Command/Message Protocol"}, 
    {"pcmail-srv", 158, "PCMail Server"}, 
    {"nss-routing", 159, "NSS-Routing"}, 
    {"sgmp-traps", 160, "SGMP-TRAPS"}, 
    {"snmp", 161, "SNMP"},
    {"snmptrap", 162, "SNMPTRAP"}, 
    {"cmip-man", 163, "CMIP Manager"}, 
    {"cmip-agent", 164, "CMIP Agent"}, 
    {"xns-courier", 165, "Xerox"}, 
    {"s-net", 166, "Sirius Systems"}, 
    {"namp", 167, "NAMP"},
    {"rsvd", 168, "RSVD"}, 
    {"send", 169, "SEND"}, 
    {"print-srv", 170, "Network PostScript"}, 
    {"multiplex", 171, "Network Innovations Multiplex"}, 
    {"cl/1", 172, "Network Innovations CL/1"}, 
    {"xyplex-mux", 173, "Xyplex"}, 
    {"mailq", 174, "MAILQ"}, 
    {"vmnet", 175, "VMNET"}, 
    {"genrad-mux", 176, "GENRAD-MUX"}, 
    {"xdmcp", 177, "X Display Manager Control Protocol"}, 
    {"nextstep", 178, "NextStep Window Server"}, 
    {"bgp", 179, "Border Gateway Protocol"}, 
    {"ris", 180, "Intergraph"}, 
    {"unify", 181, "Unify"}, 
    {"audit", 182, "Unisys Audit SITP"}, 
    {"ocbinder", 183, "OCBinder"}, 
    {"ocserver", 184, "OCServer"}, 
    {"remote-kis", 185, "Remote-KIS"}, 
    {"kis", 186, "KIS Protocol"}, 
    {"aci", 187, "Application Communication Interface"}, 
    {"mumps", 188, "Plus Five's MUMPS"},
    {"qft", 189, "Queued File Transport"}, 
    {"gacp", 190, "Gateway Access Control Protocol"}, 
    {"prospero", 191, "Prospero Directory Service"}, 
    {"osu-nms", 192, "OSU Network Monitoring System"}, 
    {"srmp", 193, "Spider Remote Monitoring Protocol"}, 
    {"irc", 194, "Internet Relay Chat Protocol"}, 
    {"dn6-nlm-aud", 195, "DNSIX Network Level Module Audit"},
    {"dn6-smm-red", 196, "DNSIX Session Mgt Module Audit Redir"}, 
    {"dls", 197, "Directory Location Service"}, 
    {"dls-mon", 198, "Directory Location Service Monitor"}, 
    {"smux", 199, "SMUX SNMP Unix Multiplexer"}, 
    {"src", 200, "IBM System Resource Controller"}, 
    {"at-rtmp", 201, "AppleTalk Routing Maintenance"}, 
    {"at-nbp", 202, "AppleTalk Name Binding"}, 
    {"at-3", 203, "AppleTalk Unused"}, 
    {"at-echo", 204, "AppleTalk Echo"}, 
    {"at-5", 205, "AppleTalk Unused"}, 
    {"at-zis", 206, "AppleTalk Zone Information"}, 
    {"at-7", 207, "AppleTalk Unused"}, 
    {"at-8", 208, "AppleTalk Unused"}, 
    {"qmtp", 209, "The Quick Mail Transfer Protocol"}, 
    {"z39.50", 210, "ANSI Z39.50"}, 
    {"914c/g", 211, "Texas Instruments 914C/G Terminal"}, 
    {"anet", 212, "ATEXSSTR"}, 
    {"ipx", 213, "IPX"}, 
    {"vmpwscs", 214, "VM PWSCS"}, 
    {"softpc", 215, "Insignia Solutions"},
    {"CAIlic", 216, "Computer Associates Int'l License Server"}, 
    {"dbase", 217, "dBASE Unix"}, 
    {"mpp", 218, "Netix Message Posting Protocol"}, 
    {"uarps", 219, "Unisys ARPs"}, 
    {"imap3", 220, "Interactive Mail Access Protocol v3"}, 
    {"fln-spx", 221, "Berkeley rlogind with SPX auth"}, 
    {"rsh-spx", 222, "Berkeley rshd with SPX auth"}, 
    {"cdc", 223, "Certificate Distribution Center"},
    {"direct", 242, "Direct"}, 
    {"sur-meas", 243, "Survey Measurement"}, 
    {"dayna", 244, "Dayna"}, 
    {"link", 245, "LINK"}, 
    {"dsp3270", 246, "Display Systems Protocol"}, 
    {"rap", 256, "RAP"}, 
    {"set", 257, "Secure Electronic Transaction"}, 
    {"yak-chat", 258, "Yak Winsock Personal Chat"}, 
    {"esro-gen", 259, "Efficient Short Remote Operations"}, 
    {"openport", 260, "Openport"}, 
    {"nsiiops", 261, "IIOP Name Service over TLS/SSL"}, 
    {"arcisdms", 262, "Arcisdms"}, 
    {"hdap", 263, "HDAP"}, 
    {"http-mgmt", 280, "http-mgmt"}, 
    {"personal-link", 281, "Personal Link"}, 
    {"cableport-ax", 282, "Cable Port A/X"}, 
    {"entrusttime", 309, "EntrustTime"}, 
    {"pdap", 344, "Prospero Data Access Protocol"}, 
    {"pawserv", 345, "Perf Analysis Workbench"},
    {"zserv", 346, "Zebra server"}, 
    {"fatserv", 347, "Fatmen Server"}, 
    {"csi-sgwp", 348, "Cabletron Management Protocol"}, 
    {"mftp", 349, "mftp"}, 
    {"matip-type-a", 350, "MATIP Type A"}, 
    {"matip-type-b", 351, "MATIP Type B"}, 
    {"dtag-ste-sb", 352, "DTAG"}, 
    {"clearcase", 371, "Clearcase"}, 
    {"ulistproc", 372, "ListProcessor"},
    {"legent-1", 373, "Legent Corporation"}, 
    {"legent-2", 374, "Legent Corporation"}, 
    {"hassle", 375, "Hassle"}, 
    {"nip", 376, "Amiga Envoy Network Inquiry Proto"}, 
    {"tnETOS", 377, "NEC Corporation"}, 
    {"dsETOS", 378, "NEC Corporation"}, 
    {"is99c", 379, "TIA/EIA/IS-99 modem client"}, 
    {"is99s", 380, "TIA/EIA/IS-99 modem server"}, 
    {"hp-collector", 381, "hp performance data collector"}, 
    {"hp-managed-node", 382, "hp performance data managed node"}, 
    {"hp-alarm-mgr", 383, "hp performance data alarm manager"}, 
    {"arns", 384, "A Remote Network Server System"}, 
    {"ibm-app", 385, "IBM Application"}, 
    {"asa", 386, "ASA Message Router Object Def."}, 
    {"aurp", 387, "Appletalk Update-Based Routing Pro."}, 
    {"unidata-ldm", 388, "Unidata LDM Version 4"}, 
    {"ldap", 389, "Lightweight Directory Access Protocol"}, 
    {"uis", 390, "UIS"},
    {"synotics-relay", 391, "SynOptics SNMP Relay Port"}, 
    {"synotics-broker", 392, "SynOptics Port Broker Port"}, 
    {"dis", 393, "Data Interpretation System"}, 
    {"embl-ndt", 394, "EMBL Nucleic Data Transfer"}, 
    {"netcp", 395, "NETscout Control Protocol"}, 
    {"netware-ip", 396, "Novell Netware over IP"}, 
    {"mptn", 397, "Multi Protocol Trans. Net."}, 
    {"kryptolan", 398, "Kryptolan"}, 
    {"iso-tsap-c2", 399, "ISO Transport Class 2 Non-Control over TCP"}, 
    {"work-sol", 400, "Workstation Solutions"},
    {"ups", 401, "Uninterruptible Power Supply"}, 
    {"genie", 402, "Genie Protocol"}, 
    {"decap", 403, "decap"}, 
    {"nced", 404, "nced"}, 
    {"ncld", 405, "ncld"}, 
    {"imsp", 406, "Interactive Mail Support Protocol"}, 
    {"timbuktu", 407, "Timbuktu"}, 
    {"prm-sm", 408, "Prospero Resource Manager Sys. Man."}, 
    {"prm-nm", 409, "Prospero Resource Manager Node Man."}, 
    {"decladebug", 410, "DECLadebug Remote Debug Protocol"}, 
    {"rmt", 411, "Remote MT Protocol"}, 
    {"synoptics-trap", 412, "Trap Convention Port"}, 
    {"smsp", 413, "SMSP"}, 
    {"infoseek", 414, "InfoSeek"}, 
    {"bnet", 415, "BNet"}, 
    {"silverplatter", 416, "Silverplatter"}, 
    {"onmux", 417, "Onmux"},
    {"hyper-g", 418, "Hyper-G"}, 
    {"ariel1", 419, "Ariel"}, 
    {"smpte", 420, "SMPTE"}, 
    {"ariel2", 421, "Ariel"}, 
    {"ariel3", 422, "Ariel"}, 
    {"opc-job-start", 423, "IBM Operations Planning and Control Start"}, 
    {"opc-job-track", 424, "IBM Operations Planning and Control Track"}, 
    {"icad-el", 425, "ICAD"}, 
    {"smartsdp", 426, "smartsdp"}, 
    {"svrloc", 427, "Server Location"}, 
    {"ocs_cmu", 428, "OCS_CMU"},
    {"ocs_amu", 429, "OCS_AMU"}, 
    {"utmpsd", 430, "UTMPSD"}, 
    {"utmpcd", 431, "UTMPCD"}, 
    {"iasd", 432, "IASD"}, 
    {"nnsp", 433, "NNSP"}, 
    {"mobileip-agent", 434, "MobileIP-Agent"}, 
    {"mobilip-mn", 435, "MobilIP-MN"}, 
    {"dna-cml", 436, "DNA-CML"}, 
    {"comscm", 437, "comscm"}, 
    {"dsfgw", 438, "dsfgw"}, 
    {"dasp", 439, "dasp Thomas Obermair"}, 
    {"sgcp", 440, "sgcp"}, 
    {"decvms-sysmgt", 441, "decvms-sysmgt"}, 
    {"cvc_hostd", 442, "cvc_hostd"}, 
    {"https", 443, "http protocol over TLS/SSL"}, 
    {"snpp", 444, "Simple Network Paging Protocol"},
    {"microsoft-ds", 445, "Microsoft-DS"}, 
    {"ddm-rdb", 446, "DDM-RDB"}, 
    {"ddm-dfm", 447, "DDM-RFM"}, 
    {"ddm-byte", 448, "DDM-BYTE"}, 
    {"as-servermap", 449, "AS Server Mapper"}, 
    {"tserver", 450, "TServer"}, 
    {"sfs-smp-net", 451, "Cray Network Semaphore server"}, 
    {"sfs-config", 452, "Cray SFS config server"}, 
    {"creativeserver", 453, "CreativeServer"}, 
    {"contentserver", 454, "ContentServer"}, 
    {"creativepartnr", 455, "CreativePartnr"}, 
    {"macon-tcp", 456, "macon-tcp"},
    {"scohelp", 457, "scohelp"}, 
    {"appleqtc", 458, "apple quick time"}, 
    {"ampr-rcmd", 459, "ampr-rcmd"}, 
    {"skronk", 460, "skronk"}, 
    {"datasurfsrv", 461, "DataRampSrv"}, 
    {"datasurfsrvsec", 462, "DataRampSrvSec"}, 
    {"alpes", 463, "alpes"}, 
    {"kpasswd", 464, "kpasswd"}, 
    {"smtps", 465, "smtp protocol over TLS/SSL (was ssmtp)"}, 
    {"digital-vrc", 466, "digital-vrc"}, 
    {"mylex-mapd", 467, "mylex-mapd"}, 
    {"photuris", 468, "proturis"}, 
    {"rcp", 469, "Radio Control Protocol"}, 
    {"scx-proxy", 470, "scx-proxy"}, 
    {"mondex", 471, "Mondex"},
    {"ljk-login", 472, "ljk-login"}, 
    {"hybrid-pop", 473, "hybrid-pop"}, 
    {"tn-tl-w1", 474, "tn-tl-w1"}, 
    {"tcpnethaspsrv", 475, "tcpnethaspsrv"}, 
    {"tcpnethaspsrv", 475, "tcpnethaspsrv"}, 
    {"tn-tl-fd1", 476, "tn-tl-fd1"}, 
    {"ss7ns", 477, "ss7ns"}, 
    {"spsc", 478, "spsc"}, 
    {"iafserver", 479, "iafserver"}, 
    {"iafdbase", 480, "iafdbase"}, 
    {"ph", 481, "Ph service"}, 
    {"bgs-nsi", 482, "bgs-nsi"}, 
    {"ulpnet", 483, "ulpnet"}, 
    {"integra-sme", 484, "Integra Software Management Environment"}, 
    {"powerburst", 485, "Air Soft Power Burst"}, 
    {"avian", 486, "avian"}, 
    {"saft", 487, "saft"}, 
    {"gss-http", 488, "gss-http"}, 
    {"nest-protocol", 489, "nest-protocol"}, 
    {"micom-pfs", 490, "micom-pfs"}, 
    {"go-login", 491, "go-login"}, 
    {"ticf-1", 492, "Transport Independent Convergence for FNA"}, 
    {"ticf-2", 493, "Transport Independent Convergence for FNA"}, 
    {"pov-ray", 494, "POV-Ray"}, 
    {"intecourier", 495, "intecourier"}, 
    {"pim-rp-disc", 496, "PIM-RP-DISC"}, 
    {"dantz", 497, "dantz"},
    {"siam", 498, "siam"}, 
    {"iso-ill", 499, "ISO ILL Protocol"}, 
    {"isakmp", 500, "isakmp"}, 
    {"stmf", 501, "STMF"}, 
    {"asa-appl-proto", 502, "asa-appl-proto"}, 
    {"intrinsa", 503, "Intrinsa"}, 
    {"citadel", 504, "citadel"}, 
    {"mailbox-lm", 505, "mailbox-lm"}, 
    {"ohimsrv", 506, "ohimsrv"}, 
    {"crs", 507, "crs"}, 
    {"xvttp", 508, "xvttp"}, 
    {"snare", 509, "snare"}, 
    {"fcp", 510, "FirstClass Protocol"}, 
    {"mynet", 511, "mynet-as"}, 
    {"exec", 512, "remote process execution;"}, 
    {"login", 513, "remote login a la telnet;"}, 
    {"shell", 514, "cmd"}, 
    {"printer", 515, "spooler"}, 
    {"videotex", 516, "videotex"}, 
    {"talk", 517, "like tenex link, but across"}, //?
    {"ntalk", 518, "ntalk"},
    {"utime", 519, "unixtime"}, 
    {"efs", 520, "extended file name server"}, 
    {"ripng", 521, "ripng"}, 
    {"ulp", 522, "ULP"}, 
    {"ibm-db2", 523, "IBM-DB2"}, 
    {"ibm-db2", 523, "IBM-DB2"},
    {"ncp", 524, "NCP"}, 
    {"timed", 525, "timeserver"}, 
    {"tempo", 526, "newdate"}, 
    {"stx", 527, "Stock IXChange"}, 
    {"custix", 528, "Customer IXChange"}, 
    {"irc-serv", 529, "IRC-SERV"}, 
    {"irc-serv", 529, "IRC-SERV"}, 
    {"courier", 530, "rpc"}, 
    {"conference", 531, "chat"}, 
    {"netnews", 532, "readnews"}, 
    {"netwall", 533, "for emergency broadcasts"}, 
    {"mm-admin", 534, "MegaMedia Admin"}, 
    {"iiop", 535, "iiop"}, 
    {"opalis-rdv", 536, "opalis-rdv"}, 
    {"nmsp", 537, "Networked Media Streaming Protocol"}, 
    {"gdomap", 538, "gdomap"}, 
    {"apertus-ldp", 539, "Apertus Technologies Load Determination"}, 
    {"uucp", 540, "uucpd"}, 
    {"uucp-rlogin", 541, "uucp-rlogin"}, 
    {"commerce", 542, "commerce"},
    {"klogin", 543, "klogin"}, 
    {"kshell", 544, "krcmd"}, 
    {"appleqtcsrvr", 545, "appleqtcsrvr"}, 
    {"dhcpv6-client", 546, "DHCPv6 Client"}, 
    {"dhcpv6-server", 547, "DHCPv6 Server"}, 
    {"afpovertcp", 548, "AFP over TCP"}, 
    {"idfp", 549, "IDFP"},
    {"new-rwho", 550, "new-who"}, 
    {"cybercash", 551, "cybercash"}, 
    {"deviceshare", 552, "deviceshare"}, 
    {"pirp", 553, "pirp"}, 
    {"rtsp", 554, "Real Time Stream Control Protocol"}, 
    {"dsf", 555, "dsf"}, 
    {"remotefs", 556, "rfs server"}, 
    {"openvms-sysipc", 557, "openvms-sysipc"}, 
    {"sdnskmp", 558, "SDNSKMP"}, 
    {"teedtap", 559, "TEEDTAP"}, 
    {"rmonitor", 560, "rmonitord"}, 
    {"monitor", 561, "monitor"}, 
    {"chshell", 562, "chcmd"}, 
    {"nntps", 563, "nntp protocol over TLS/SSL (was snntp)"}, 
    {"9pfs", 564, "plan 9 file service"}, 
    {"whoami", 565, "whoami"}, 
    {"streettalk", 566, "streettalk"}, 
    {"banyan-rpc", 567, "banyan-rpc"}, 
    {"ms-shuttle", 568, "microsoft shuttle"}, 
    {"ms-rome", 569, "microsoft rome"},
    {"meter", 570, "demon"}, 
    {"meter", 571, "udemon"}, 
    {"sonar", 572, "sonar"}, 
    {"banyan-vip", 573, "banyan-vip"}, 
    {"ftp-agent", 574, "FTP Software Agent System"}, 
    {"vemmi", 575, "VEMMI"}, 
    {"ipcd", 576, "ipcd"},
    {"vnas", 577, "vnas"}, 
    {"ipdd", 578, "ipdd"}, 
    {"decbsrv", 579, "decbsrv"}, 
    {"sntp-heartbeat", 580, "SNTP HEARTBEAT"}, 
    {"bdp", 581, "Bundle Discovery Protocol"}, 
    {"scc-security", 582, "SCC Security"}, 
    {"philips-vc", 583, "Philips Video-Conferencing"}, 
    {"keyserver", 584, "Key Server"}, 
    {"imap4-ssl", 585, "IMAP4+SSL"}, 
    {"password-chg", 586, "Password Change"}, 
    {"submission", 587, "Submission"}, 
    {"ipcserver", 600, "Sun IPC server"}, 
    {"urm", 606, "Cray Unified Resource Manager"}, 
    {"nqs", 607, "nqs"}, 
    {"sift-uft", 608, "Sender-Initiated/Unsolicited File Transfer"}, 
    {"npmp-trap", 609, "npmp-trap"}, 
    {"npmp-local", 610, "npmp-local"}, 
    {"npmp-gui", 611, "npmp-gui"}, 
    {"hmmp-ind", 612, "HMMP Indication"}, 
    {"hmmp-op", 613, "HMMP Operation"},
    {"sshell", 614, "SSLshell"}, 
    {"sco-inetmgr", 615, "Internet Configuration Manager"}, 
    {"sco-sysmgr", 616, "SCO System Administration Server"}, 
    {"sco-dtmgr", 617, "SCO Desktop Administration Server"}, 
    {"dei-icda", 618, "DEI-ICDA"}, 
    {"digital-evm", 619, "Digital EVM"}, 
    {"sco-websrvrmgr", 620, "SCO WebServer Manager"},
    {"escp-ip", 621, "ESCP"}, 
    {"servstat", 633, "Service Status update (Sterling Software)"}, 
    {"ginad", 634, "ginad"}, 
    {"rlzdbase", 635, "RLZ DBase"}, 
    {"ldaps", 636, "ldap protocol over TLS/SSL (was sldap)"}, 
    {"lanserver", 637, "lanserver"}, 
    {"mdqs", 666, "mdqs"}, 
    {"doom", 666, "doom Id Software"}, 
    {"disclose", 667, "campaign contribution disclosures -"}, 
    {"mecomm", 668, "MeComm"}, 
    {"meregister", 669, "MeRegister"}, 
    {"vacdsm-sws", 670, "VACDSM-SWS"}, 
    {"vacdsm-app", 671, "VACDSM-APP"}, 
    {"vpps-qua", 672, "VPPS-QUA"}, 
    {"cimplex", 673, "CIMPLEX"}, 
    {"acap", 674, "ACAP"}, 
    {"elcsd", 704, "errlog copy/server daemon"}, 
    {"agentx", 705, "AgentX"}, 
    {"entrust-kmsh", 709, "Entrust Key Management Service Handler"}, 
    {"entrust-ash", 710, "Entrust Administration Service Handler"},
    {"netviewdm1", 729, "IBM NetView DM/6000 Server/Client"}, 
    {"netviewdm2", 730, "IBM NetView DM/6000 send}"}, 
    {"netviewdm3", 731, "IBM NetView DM/6000 receive}"}, 
    {"netgw", 741, "netGW"}, 
    {"netrcs", 742, "Network based Rev. Cont. Sys."}, 
    {"flexlm", 744, "Flexible License Manager"}, 
    {"fujitsu-dev", 747, "Fujitsu Device Control"},
    {"ris-cm", 748, "Russell Info Sci Calendar Manager"}, 
    {"kerberos-adm", 749, "kerberos administration"}, 
    {"rfile", 750, "rfile"}, 
    {"pump", 751, "pump"}, 
    {"qrh", 752, "qrh"}, 
    {"rrh", 753, "rrh"}, 
    {"tell", 754, "send"}, 
    {"nlogin", 758, "nlogin"}, 
    {"con", 759, "con"}, 
    {"ns", 760, "ns"}, 
    {"rxe", 761, "rxe"}, 
    {"quotad", 762, "quotad"}, 
    {"cycleserv", 763, "cycleserv"}, 
    {"omserv", 764, "omserv"}, 
    {"webster", 765, "webster"}, 
    {"phonebook", 767, "phone"}, 
    {"vid", 769, "vid"}, 
    {"cadlock", 770, "cadlock"}, 
    {"rtip", 771, "rtip"}, 
    {"cycleserv2", 772, "cycleserv2"}, 
    {"submit", 773, "submit"}, 
    {"rpasswd", 774, "rpasswd"}, 
    {"entomb", 775, "entomb"}, 
    {"wpages", 776, "wpages"}, 
    {"wpgs", 780, "wpgs"}, 
    {"concert", 786, "Concert"}, 
    {"mdbs_daemon", 800, "mdbs_daemon"},
    {"device", 801, "device"}, 
    {"iclcnet-locate", 886, "ICL coNETion locate server"}, 
    {"iclcnet_svinfo", 887, "ICL coNETion server info"}, 
    {"accessbuilder", 888, "AccessBuilder"}, 
    {"xact-backup", 911, "xact-backup"}, 
    {"xact-backup", 911, "xact-backup"}, 
    {"ftps-data", 989, "ftp protocol, data"},
    {"ftps", 990, "ftp protocol, control"},
    {"nas", 991, "Netnews Administration System"},
    {"telnets", 992, "telnet protocol over TLS/SSL"}, 
    {"imaps", 993, "imap4 protocol over TLS/SSL"}, 
    {"ircs", 994, "irc protocol over TLS/SSL"}, 
    {"pop3s", 995, "pop3 protocol over TLS/SSL (was spop3)"}, 
    {"vsinet", 996, "vsinet"}, 
    {"maitrd", 997, "maitrd"}, 
    {"busboy", 998, "busboy"}, 
    {"garcon", 999, "garcon"}, 
    {"puprouter", 999, "puprouter"}, 
    {"cadlock", 1000, "cadlock"}, 
    {"", 1023, "Reserved"}, 
    {"", 1024, "Reserved"}, 
    {"blackjack", 1025, "network blackjack"}, 
    {"iad1", 1030, "BBN IAD"}, 
    {"iad2", 1031, "BBN IAD"}, 
    {"iad3", 1032, "BBN IAD"}, 
    {"neod1", 1047, "Sun's NEO Object Request Broker"}, 
    {"neod2", 1048, "Sun's NEO Object Request Broker"}, 
    {"nim", 1058, "nim"}, 
    {"nimreg", 1059, "nimreg"}, 
    {"instl_boots", 1067, "Installation Bootstrap Proto. Serv."}, 
    {"instl_bootc", 1068, "Installation Bootstrap Proto. Cli."}, 
    {"socks", 1080, "Socks"}, 
    {"ansoft-lm-1", 1083, "Anasoft License Manager"}, 
    {"ansoft-lm-2", 1084, "Anasoft License Manager"}, 
    {"nfsd-status", 1110, "Cluster status info"}, 
    {"lmsocialserver", 1111, "LM Social Server"}, 
    {"murray", 1123, "Murray"}, 
    {"nfa", 1155, "Network File Access"}, 
    {"mc-client", 1180, "Millicent Client Proxy"}, 
    {"lupa", 1212, "lupa"}, 
    {"nerv", 1222, "SNI R&D network"}, 
    {"hermes", 1248, "hermes"}, 
    {"bmc_patroldb", 1313, "BMC_PATROLDB"}, 
    {"pdps", 1314, "Photoscript Distributed Printing System"}, 
    {"vpjp", 1345, "VPJP"}, 
    {"alta-ana-lm", 1346, "Alta Analytics License Manager"}, 
    {"bbn-mmc", 1347, "multi media conferencing"}, 
    {"bbn-mmx", 1348, "multi media conferencing"}, 
    {"sbook", 1349, "Registration Network Protocol"}, 
    {"editbench", 1350, "Registration Network Protocol"}, 
    {"equationbuilder", 1351, "Digital Tool Works (MIT)"}, 
    {"lotusnote", 1352, "Lotus Note"}, 
    {"relief", 1353, "Relief Consulting"}, 
    {"rightbrain", 1354, "RightBrain Software"}, 
    {"intuitive edge", 1355, "Intuitive Edge"}, 
    {"cuillamartin", 1356, "CuillaMartin Company"}, 
    {"pegboard", 1357, "Electronic PegBoard"}, 
    {"connlcli", 1358, "CONNLCLI"}, 
    {"ftsrv", 1359, "FTSRV"}, 
    {"mimer", 1360, "MIMER"}, 
    {"linx", 1361, "LinX"}, 
    {"timeflies", 1362, "TimeFlies"}, 
    {"ndm-requester", 1363, "Network DataMover Requester"}, 
    {"ndm-server", 1364, "Network DataMover Server"}, 
    {"adapt-sna", 1365, "Network Software Associates"}, 
    {"netware-csp", 1366, "Novell NetWare Comm Service Platform"}, 
    {"dcs", 1367, "DCS"}, 
    {"screencast", 1368, "ScreenCast"}, 
    {"gv-us", 1369, "GlobalView to Unix Shell"}, 
    {"us-gv", 1370, "Unix Shell to GlobalView"}, 
    {"fc-cli", 1371, "Fujitsu Config Protocol"}, 
    {"fc-ser", 1372, "Fujitsu Config Protocol"}, 
    {"chromagrafx", 1373, "Chromagrafx"}, 
    {"molly", 1374, "EPI Software Systems"}, 
    {"bytex", 1375, "Bytex"}, 
    {"ibm-pps", 1376, "IBM Person to Person Software"}, 
    {"cichlid", 1377, "Cichlid License Manager"}, 
    {"elan", 1378, "Elan License Manager"}, 
    {"dbreporter", 1379, "Integrity Solutions"}, 
    {"telesis-licman", 1380, "Telesis Network License Manager"}, 
    {"apple-licman", 1381, "Apple Network License Manager"}, 
    {"udt_os", 1382, "udt_os"}, 
    {"gwha", 1383, "GW Hannaway Network License Manager"}, 
    {"os-licman", 1384, "Objective Solutions License Manager"}, 
    {"atex_elmd", 1385, "Atex Publishing License Manager"}, 
    {"checksum", 1386, "CheckSum License Manager"}, 
    {"cadsi-lm", 1387, "Computer Aided Design Software Inc LM"}, 
    {"objective-dbc", 1388, "Objective Solutions DataBase Cache"}, 
    {"iclpv-dm", 1389, "Document Manager"}, 
    {"iclpv-sc", 1390, "Storage Controller"}, 
    {"iclpv-sas", 1391, "Storage Access Server"}, 
    {"iclpv-pm", 1392, "Print Manager"}, 
    {"iclpv-nls", 1393, "Network Log Server"}, 
    {"iclpv-nlc", 1394, "Network Log Client"}, 
    {"iclpv-wsm", 1395, "PC Workstation Manager software"}, 
    {"dvl-activemail", 1396, "DVL Active Mail"}, 
    {"audio-activmail", 1397, "Audio Active Mail"}, 
    {"video-activmail", 1398, "Video Active Mail"}, 
    {"cadkey-licman", 1399, "Cadkey License Manager"}, 
    {"cadkey-tablet", 1400, "Cadkey Tablet Daemon"}, 
    {"goldleaf-licman", 1401, "Goldleaf License Manager"}, 
    {"prm-sm-np", 1402, "Prospero Resource Manager"}, 
    {"prm-nm-np", 1403, "Prospero Resource Manager"}, 
    {"igi-lm", 1404, "Infinite Graphics License Manager"}, 
    {"ibm-res", 1405, "IBM Remote Execution Starter"}, 
    {"netlabs-lm", 1406, "NetLabs License Manager"}, 
    {"dbsa-lm", 1407, "DBSA License Manager"}, 
    {"sophia-lm", 1408, "Sophia License Manager"}, 
    {"here-lm", 1409, "Here License Manager"}, 
    {"hiq", 1410, "HiQ License Manager"}, 
    {"af", 1411, "AudioFile"}, 
    {"innosys", 1412, "InnoSys"}, 
    {"innosys-acl", 1413, "Innosys-ACL"}, 
    {"ibm-mqseries", 1414, "IBM MQSeries"}, 
    {"dbstar", 1415, "DBStar"}, 
    {"novell-lu6.2", 1416, "Novell LU6.2"}, 
    {"timbuktu-srv1", 1417, "Timbuktu Service 1 Port"}, 
    {"timbuktu-srv1", 1417, "Timbuktu Service 1 Port"}, 
    {"timbuktu-srv2", 1418, "Timbuktu Service 2 Port"}, 
    {"timbuktu-srv3", 1419, "Timbuktu Service 3 Port"}, 
    {"timbuktu-srv4", 1420, "Timbuktu Service 4 Port"}, 
    {"gandalf-lm", 1421, "Gandalf License Manager"}, 
    {"autodesk-lm", 1422, "Autodesk License Manager"}, 
    {"essbase", 1423, "Essbase Arbor Software"}, 
    {"hybrid", 1424, "Hybrid Encryption Protocol"}, 
    {"zion-lm", 1425, "Zion Software License Manager"}, 
    {"sais", 1426, "Satellite-data Acquisition System 1"}, 
    {"mloadd", 1427, "mloadd monitoring tool"}, 
    {"informatik-lm", 1428, "Informatik License Manager"}, 
    {"nms", 1429, "Hypercom NMS"}, 
    {"tpdu", 1430, "Hypercom TPDU"}, 
    {"rgtp", 1431, "Reverse Gossip Transport"}, 
    {"blueberry-lm", 1432, "Blueberry Software License Manager"}, 
    {"ms-sql-s", 1433, "Microsoft-SQL-Server"}, 
    {"ms-sql-m", 1434, "Microsoft-SQL-Monitor"}, 
    {"ibm-cics", 1435, "IBM CICS"}, 
    {"saism", 1436, "Satellite-data Acquisition System 2"}, 
    {"tabula", 1437, "Tabula"}, 
    {"eicon-server", 1438, "Eicon Security Agent/Server"}, 
    {"eicon-x25", 1439, "Eicon X25/SNA Gateway"}, 
    {"eicon-slp", 1440, "Eicon Service Location Protocol"}, 
    {"cadis-1", 1441, "Cadis License Management"}, 
    {"cadis-2", 1442, "Cadis License Management"}, 
    {"ies-lm", 1443, "Integrated Engineering Software"}, 
    {"marcam-lm", 1444, "Marcam License Management"}, 
    {"proxima-lm", 1445, "Proxima License Manager"}, 
    {"ora-lm", 1446, "Optical Research Associates License Manager"}, 
    {"apri-lm", 1447, "Applied Parallel Research LM"}, 
    {"oc-lm", 1448, "OpenConnect License Manager"}, 
    {"peport", 1449, "PEport"}, 
    {"dwf", 1450, "Tandem Distributed Workbench Facility"}, 
    {"infoman", 1451, "IBM Information Management"}, 
    {"gtegsc-lm", 1452, "GTE Government Systems License Man"}, 
    {"genie-lm", 1453, "Genie License Manager"}, 
    {"interhdl_elmd", 1454, "interHDL License Manager"}, 
    {"interhdl_elmd", 1454, "interHDL License Manager"}, 
    {"esl-lm", 1455, "ESL License Manager"}, 
    {"dca", 1456, "DCA"}, 
    {"valisys-lm", 1457, "Valisys License Manager"}, 
    {"nrcabq-lm", 1458, "Nichols Research Corp."}, 
    {"proshare1", 1459, "Proshare Notebook Application"}, 
    {"proshare2", 1460, "Proshare Notebook Application"}, 
    {"ibm_wrless_lan", 1461, "IBM Wireless LAN"}, 
    {"world-lm", 1462, "World License Manager"}, 
    {"nucleus", 1463, "Nucleus"}, 
    {"msl_lmd", 1464, "MSL License Manager"}, 
    {"pipes", 1465, "Pipes Platform"}, 
    {"oceansoft-lm", 1466, "Ocean Software License Manager"}, 
    {"csdmbase", 1467, "CSDMBASE"}, 
    {"csdm", 1468, "CSDM"}, 
    {"aal-lm", 1469, "Active Analysis Limited License Manager"}, 
    {"uaiact", 1470, "Universal Analytics"}, 
    {"csdmbase", 1471, "csdmbase"}, 
    {"csdm", 1472, "csdm"}, 
    {"openmath", 1473, "OpenMath"}, 
    {"telefinder", 1474, "Telefinder"}, 
    {"taligent-lm", 1475, "Taligent License Manager"}, 
    {"clvm-cfg", 1476, "clvm-cfg"}, 
    {"ms-sna-server", 1477, "ms-sna-server"}, 
    {"ms-sna-base", 1478, "ms-sna-base"}, 
    {"dberegister", 1479, "dberegister"}, 
    {"pacerforum", 1480, "PacerForum"}, 
    {"airs", 1481, "AIRS"}, 
    {"miteksys-lm", 1482, "Miteksys License Manager"}, 
    {"afs", 1483, "AFS License Manager"}, 
    {"confluent", 1484, "Confluent License Manager"}, 
    {"lansource", 1485, "LANSource"}, 
    {"nms_topo_serv", 1486, "nms_topo_serv"}, 
    {"localinfosrvr", 1487, "LocalInfoSrvr"}, 
    {"docstor", 1488, "DocStor"}, 
    {"dmdocbroker", 1489, "dmdocbroker"}, 
    {"insitu-conf", 1490, "insitu-conf"}, 
    {"anynetgateway", 1491, "anynetgateway"}, 
    {"stone-design-1", 1492, "stone-design-1"}, 
    {"netmap_lm", 1493, "netmap_lm"}, 
    {"ica", 1494, "ica"}, 
    {"cvc", 1495, "cvc"}, 
    {"liberty-lm", 1496, "liberty-lm"}, 
    {"rfx-lm", 1497, "rfx-lm"}, 
    {"watcom-sql", 1498, "Watcom-SQL"}, 
    {"fhc", 1499, "Federico Heinz Consultora"}, 
    {"vlsi-lm", 1500, "VLSI License Manager"}, 
    {"saiscm", 1501, "Satellite-data Acquisition System 3"}, 
    {"shivadiscovery", 1502, "Shiva"}, 
    {"imtc-mcs", 1503, "Databeam"}, 
    {"evb-elm", 1504, "EVB Software Engineering License Manager"}, 
    {"funkproxy", 1505, "Funk Software, Inc."},
    {"utcd", 1506, "Universal Time daemon (utcd)"},
    {"symplex", 1507, "symplex"}, 
    {"diagmond", 1508, "diagmond"}, 
    {"robcad-lm", 1509, "Robcad, Ltd. License Manager"},
    {"mvx-lm", 1510, "Midland Valley Exploration Ltd. Lic. Man."},
    {"3l-l1", 1511, "3l-l1"}, 
    {"wins", 1512, "Microsoft's Windows Internet Name Service"}, 
    {"fujitsu-dtc", 1513, "Fujitsu Systems Business of America, Inc"},
    {"fujitsu-dtcns", 1514, "Fujitsu Systems Business of America, Inc"},
    {"ifor-protocol", 1515, "ifor-protocol"}, 
    {"vpad", 1516, "Virtual Places Audio data"}, 
    {"vpac", 1517, "Virtual Places Audio control"}, 
    {"vpvd", 1518, "Virtual Places Video data"}, 
    {"vpvc", 1519, "Virtual Places Video control"}, 
    {"atm-zip-office", 1520, "atm zip office"}, 
    {"ncube-lm", 1521, "nCube License Manager"}, 
    {"ricardo-lm", 1522, "Ricardo North America License Manager"}, 
    {"cichild-lm", 1523, "cichild"}, 
    {"ingreslock", 1524, "ingres"}, 
    {"orasrv", 1525, "oracle"}, 
    {"prospero-np", 1525, "Prospero Directory Service non-priv"}, 
    {"pdap-np", 1526, "Prospero Data Access Prot non-priv"}, 
    {"tlisrv", 1527, "oracle"}, 
    {"mciautoreg", 1528, "micautoreg"}, 
    {"coauthor", 1529, "oracle"}, 
    {"rap-service", 1530, "rap-service"}, 
    {"rap-listen", 1531, "rap-listen"}, 
    {"miroconnect", 1532, "miroconnect"}, 
    {"virtual-places", 1533, "Virtual Places Software"}, 
    {"micromuse-lm", 1534, "micromuse-lm"}, 
    {"ampr-info", 1535, "ampr-info"}, 
    {"ampr-inter", 1536, "ampr-inter"}, 
    {"sdsc-lm", 1537, "isi-lm"}, 
    {"3ds-lm", 1538}, //", 3ds-lm"}
    {"intellistor-lm", 1539, "Intellistor License Manager"}, 
    {"rds", 1540, "rds"}, 
    {"rds2", 1541, "rds2"}, 
    {"gridgen-elmd", 1542, "gridgen-elmd"}, 
    {"simba-cs", 1543, "simba-cs"}, 
    {"aspeclmd", 1544, "aspeclmd"}, 
    {"vistium-share", 1545, "vistium-share"}, 
    {"abbaccuray", 1546, "abbaccuray"}, 
    {"laplink", 1547, "laplink"}, 
    {"axon-lm", 1548, "Axon License Manager"}, 
    {"shivahose", 1549, "Shiva Hose"}, 
    {"3m-image-lm", 1550, "Image Storage license manager 3M Company"}, 
    {"hecmtl-db", 1551, "HECMTL-DB"}, 
    {"pciarray", 1552, "pciarray"}, 
    {"sna-cs", 1553, "sna-cs"}, 
    {"caci-lm", 1554, "CACI Products Company License Manager"}, 
    {"livelan", 1555, "livelan"}, 
    {"ashwin", 1556, "AshWin CI Tecnologies"}, 
    {"arbortext-lm", 1557, "ArborText License Manager"}, 
    {"xingmpeg", 1558, "xingmpeg"}, 
    {"web2host", 1559, "web2host"}, 
    {"asci-val", 1560, "asci-val"}, 
    {"facilityview", 1561, "facilityview"}, 
    {"pconnectmgr", 1562, "pconnectmgr"}, 
    {"cadabra-lm", 1563, "Cadabra License Manager"}, 
    {"pay-per-view", 1564, "Pay-Per-View"}, 
    {"winddlb", 1565, "WinDD"}, 
    {"corelvideo", 1566, "CORELVIDEO"}, 
    {"jlicelmd", 1567, "jlicelmd"}, 
    {"tsspmap", 1568, "tsspmap"}, 
    {"ets", 1569, "ets"}, 
    {"orbixd", 1570, "orbixd"}, 
    {"rdb-dbs-disp", 1571, "Oracle Remote Data Base"}, 
    {"chip-lm", 1572, "Chipcom License Manager"}, 
    {"itscomm-ns", 1573, "itscomm-ns"}, 
    {"mvel-lm", 1574, "mvel-lm"}, 
    {"oraclenames", 1575, "oraclenames"}, 
    {"moldflow-lm", 1576, "moldflow-lm"}, 
    {"hypercube-lm", 1577, "hypercube-lm"}, 
    {"jacobus-lm", 1578, "Jacobus License Manager"}, 
    {"ioc-sea-lm", 1579, "ioc-sea-lm"}, 
    {"ioc-sea-lm", 1579, "ioc-sea-lm"}, 
    {"tn-tl-r1", 1580, "tn-tl-r1"}, 
    {"vmf-msg-port", 1581, "vmf-msg-port"}, 
    {"msims", 1582, "MSIMS"}, 
    {"simbaexpress", 1583, "simbaexpress"}, 
    {"tn-tl-fd2", 1584, "tn-tl-fd2"}, 
    {"intv", 1585, "intv"}, 
    {"ibm-abtact", 1586, "ibm-abtact"}, 
    {"pra_elmd", 1587, "pra_elmd"}, 
    {"triquest-lm", 1588, "triquest-lm"}, 
    {"vqp", 1589, "VQP"}, 
    {"gemini-lm", 1590, "gemini-lm"}, 
    {"ncpm-pm", 1591, "ncpm-pm"}, 
    {"commonspace", 1592, "commonspace"}, 
    {"mainsoft-lm", 1593, "mainsoft-lm"}, 
    {"sixtrak", 1594, "sixtrak"}, 
    {"radio", 1595, "radio"}, 
    {"radio-sm", 1596, "radio-sm"}, 
    {"orbplus-iiop", 1597, "orbplus-iiop"}, 
    {"picknfs", 1598, "picknfs"}, 
    {"simbaservices", 1599, "simbaservices"}, 
    {"issd", 1600, "issd"}, 
    {"aas", 1601, "aas"}, 
    {"inspect", 1602, "inspect"}, 
    {"picodbc", 1603, "pickodbc"}, 
    {"icabrowser", 1604, "icabrowser"}, 
    {"slp", 1605, "Salutation Manager (Salutation Protocol)"}, 
    {"slm-api", 1606, "Salutation Manager (SLM-API)"}, 
    {"stt", 1607, "stt"}, 
    {"smart-lm", 1608, "Smart Corp. License Manager"}, 
    {"isysg-lm", 1609, "isysg-lm"}, 
    {"taurus-wh", 1610, "taurus-wh"}, 
    {"ill", 1611, "Inter Library Loan"}, 
    {"netbill-trans", 1612, "NetBill Transaction Server"}, 
    {"netbill-keyrep", 1613, "NetBill Key Repository"}, 
    {"netbill-cred", 1614, "NetBill Credential Server"}, 
    {"netbill-auth", 1615, "NetBill Authorization Server"}, 
    {"netbill-prod", 1616, "NetBill Product Server"}, 
    {"nimrod-agent", 1617, "Nimrod Inter-Agent Communication"}, 
    {"skytelnet", 1618, "skytelnet"}, 
    {"xs-openstorage", 1619, "xs-openstorage"}, 
    {"faxportwinport", 1620, "faxportwinport"}, 
    {"softdataphone", 1621, "softdataphone"}, 
    {"ontime", 1622, "ontime"}, 
    {"jaleosnd", 1623, "jaleosnd"}, 
    {"udp-sr-port", 1624, "udp-sr-port"}, 
    {"svs-omagent", 1625, "svs-omagent"}, 
    {"cncp", 1636, "CableNet Control Protocol"}, 
    {"cnap", 1637, "CableNet Admin Protocol"}, 
    {"cnip", 1638, "CableNet Info Protocol"}, 
    {"cert-initiator", 1639, "cert-initiator"}, 
    {"cert-responder", 1640, "cert-responder"}, 
    {"invision", 1641, "InVision"}, 
    {"isis-am", 1642, "isis-am"}, 
    {"isis-ambc", 1643, "isis-ambc"}, 
    {"saiseh", 1644, "Satellite-data Acquisition System 4"}, 
    {"datametrics", 1645, "datametrics"}, 
    {"sa-msg-port", 1646, "sa-msg-port"}, 
    {"rsap", 1647, "rsap"}, 
    {"concurrent-lm", 1648, "concurrent-lm"}, 
    {"inspect", 1649, "inspect"}, 
    {"nkd", 1650, "nkd"}, 
    {"shiva_confsrvr", 1651, "shiva_confsrvr"}, 
    {"xnmp", 1652, "xnmp"}, 
    {"alphatech-lm", 1653, "alphatech-lm"}, 
    {"stargatealerts", 1654, "stargatealerts"}, 
    {"dec-mbadmin", 1655, "dec-mbadmin"}, 
    {"dec-mbadmin-h", 1656, "dec-mbadmin-h"}, 
    {"fujitsu-mmpdc", 1657, "fujitsu-mmpdc"}, 
    {"sixnetudr", 1658, "sixnetudr"}, 
    {"sg-lm", 1659, "Silicon Grail License Manager"}, 
    {"skip-mc-gikreq", 1660, "skip-mc-gikreq"}, 
    {"netview-aix-1", 1661, "netview-aix-1"}, 
    {"netview-aix-2", 1662, "netview-aix-2"}, 
    {"netview-aix-3", 1663, "netview-aix-3"}, 
    {"netview-aix-4", 1664, "netview-aix-4"}, 
    {"netview-aix-5", 1665, "netview-aix-5"}, 
    {"netview-aix-6", 1666, "netview-aix-6"}, 
    {"netview-aix-7", 1667, "netview-aix-7"}, 
    {"netview-aix-8", 1668, "netview-aix-8"}, 
    {"netview-aix-9", 1669, "netview-aix-9"}, 
    {"netview-aix-10", 1670, "netview-aix-10"}, 
    {"netview-aix-11", 1671, "netview-aix-11"}, 
    {"netview-aix-12", 1672, "netview-aix-12"}, 
    {"proshare-mc-1", 1673, "Intel Proshare Multicast"}, 
    {"proshare-mc-2", 1674, "Intel Proshare Multicast"}, 
    {"pdp", 1675, "Pacific Data Products"}, 
    {"netcomm1", 1676, "netcomm1"}, 
    {"groupwise", 1677, "groupwise"}, 
    {"prolink", 1678, "prolink"}, 
    {"darcorp-lm", 1679, "darcorp-lm"}, 
    {"microcom-sbp", 1680, "microcom-sbp"}, 
    {"sd-elmd", 1681, "sd-elmd"}, 
    {"lanyon-lantern", 1682, "lanyon-lantern"}, 
    {"ncpm-hip", 1683, "ncpm-hip"}, 
    {"snaresecure", 1684, "SnareSecure"}, 
    {"n2nremote", 1685, "n2nremote"}, 
    {"cvmon", 1686, "cvmon"}, 
    {"nsjtp-ctrl", 1687, "nsjtp-ctrl"}, 
    {"nsjtp-data", 1688, "nsjtp-data"}, 
    {"firefox", 1689, "firefox"}, 
    {"ng-umds", 1690, "ng-umds"}, 
    {"empire-empuma", 1691, "empire-empuma"}, 
    {"sstsys-lm", 1692, "sstsys-lm"}, 
    {"rrirtr", 1693, "rrirtr"}, 
    {"rrimwm", 1694, "rrimwm"}, 
    {"rrilwm", 1695, "rrilwm"}, 
    {"rrifmm", 1696, "rrifmm"}, 
    {"rrisat", 1697, "rrisat"}, 
    {"rsvp-encap-1", 1698, "RSVP-ENCAPSULATION-1"}, 
    {"rsvp-encap-2", 1699, "RSVP-ENCAPSULATION-2"}, 
    {"mps-raft", 1700, "mps-raft"}, 
    {"l2f", 1701, "l2f"}, 
    {"deskshare", 1702, "deskshare"}, 
    {"hb-engine", 1703, "hb-engine"}, 
    {"bcs-broker", 1704, "bcs-broker"}, 
    {"slingshot", 1705, "slingshot"}, 
    {"jetform", 1706, "jetform"}, 
    {"vdmplay", 1707, "vdmplay"}, 
    {"gat-lmd", 1708, "gat-lmd"}, 
    {"centra", 1709, "centra"}, 
    {"impera", 1710, "impera"}, 
    {"pptconference", 1711, "pptconference"}, 
    {"registrar", 1712, "resource monitoring service"}, 
    {"conferencetalk", 1713, "ConferenceTalk"}, 
    {"sesi-lm", 1714, "sesi-lm"}, 
    {"houdini-lm", 1715, "houdini-lm"}, 
    {"xmsg", 1716, "xmsg"}, 
    {"fj-hdnet", 1717, "fj-hdnet"}, 
    {"h323gatedisc", 1718, "h323gatedisc"}, 
    {"h323gatestat", 1719, "h323gatestat"}, 
    {"h323hostcall", 1720, "h323hostcall"}, 
    {"caicci", 1721, "caicci"}, 
    {"hks-lm", 1722, "HKS License Manager"}, 
    {"pptp", 1723, "pptp"}, 
    {"csbphonemaster", 1724, "csbphonemaster"}, 
    {"iden-ralp", 1725, "iden-ralp"}, 
    {"iberiagames", 1726, "IBERIAGAMES"}, 
    {"iberiagames", 1726, "IBERIAGAMES"}, 
    {"winddx", 1727, "winddx"}, 
    {"telindus", 1728, "TELINDUS"}, 
    {"citynl", 1729, "CityNL License Management"}, 
    {"roketz", 1730, "roketz"}, 
    {"msiccp", 1731, "MSICCP"}, 
    {"proxim", 1732, "proxim"}, 
    {"sipat", 1733, "sipat"}, 
    {"cambertx-lm", 1734, "Camber Corporation License Management"}, 
    {"privatechat", 1735, "PrivateChat"}, 
    {"street-stream", 1736, "street-stream"}, 
    {"ultimad", 1737, "ultimad"}, 
    {"gamegen1", 1738, "GameGen1"}, 
    {"webaccess", 1739, "webaccess"}, 
    {"encore", 1740, "encore"}, 
    {"cisco-net-mgmt", 1741, "cisco-net-mgmt"}, 
    {"3Com-nsd", 1742}, //", 3Com-nsd"}
    {"cinegrfx-lm", 1743, "Cinema Graphics License Manager"}, 
    {"ncpm-ft", 1744, "ncpm-ft"}, 
    {"remote-winsock", 1745, "remote-winsock"}, 
    {"ftrapid-1", 1746, "ftrapid-1"}, 
    {"ftrapid-2", 1747, "ftrapid-2"}, 
    {"oracle-em1", 1748, "oracle-em1"}, 
    {"aspen-services", 1749, "aspen-services"}, 
    {"sslp", 1750, "Simple Socket Library's PortMaster"}, 
    {"swiftnet", 1751, "SwiftNet"}, 
    {"lofr-lm", 1752, "Leap of Faith Research License Manager"}, 
    {"translogic-lm", 1753, "Translogic License Manager"}, 
    {"oracle-em2", 1754, "oracle-em2"}, 
    {"ms-streaming", 1755, "ms-streaming"}, 
    {"capfast-lmd", 1756, "capfast-lmd"}, 
    {"cnhrp", 1757, "cnhrp"}, 
    {"tftp-mcast", 1758, "tftp-mcast"}, 
    {"spss-lm", 1759, "SPSS License Manager"}, 
    {"www-ldap-gw", 1760, "www-ldap-gw"}, 
    {"cft-0", 1761, "cft-0"}, 
    {"cft-1", 1762, "cft-1"}, 
    {"cft-2", 1763, "cft-2"}, 
    {"cft-3", 1764, "cft-3"}, 
    {"cft-4", 1765, "cft-4"}, 
    {"cft-5", 1766, "cft-5"}, 
    {"cft-6", 1767, "cft-6"}, 
    {"cft-7", 1768, "cft-7"}, 
    {"bmc-net-adm", 1769, "bmc-net-adm"}, 
    {"bmc-net-svc", 1770, "bmc-net-svc"}, 
    {"vaultbase", 1771, "vaultbase"}, 
    {"essweb-gw", 1772, "EssWeb Gateway"}, 
    {"kmscontrol", 1773, "KMSControl"}, 
    {"global-dtserv", 1774, "global-dtserv"}, 
    {"femis", 1776, "Federal Emergency Management Information System"}, 
    {"powerguardian", 1777, "powerguardian"}, 
    {"prodigy-internet", 1778, "prodigy-internet"}, 
    {"pharmasoft", 1779, "pharmasoft"}, 
    {"dpkeyserv", 1780, "dpkeyserv"}, 
    {"answersoft-lm", 1781, "answersoft-lm"}, 
    {"hp-hcip", 1782, "hp-hcip"}, 
    {"fjris", 1783, "Fujitsu Remote Install Service"}, 
    {"finle-lm", 1784, "Finle License Manager"}, 
    {"windlm", 1785, "Wind River Systems License Manager"}, 
    {"funk-logger", 1786, "funk-logger"}, 
    {"funk-license", 1787, "funk-license"}, 
    {"psmond", 1788, "psmond"}, 
    {"hello", 1789, "hello"}, 
    {"nmsp", 1790, "Narrative Media Streaming Protocol"}, 
    {"ea1", 1791, "EA1"}, 
    {"ibm-dt-2", 1792, "ibm-dt-2"}, 
    {"rsc-robot", 1793, "rsc-robot"}, 
    {"cera-bcm", 1794, "cera-bcm"}, 
    {"dpi-proxy", 1795, "dpi-proxy"}, 
    {"vocaltec-admin", 1796, "Vocaltec Server Administration"}, 
    {"uma", 1797, "UMA"}, 
    {"etp", 1798, "Event Transfer Protocol"}, 
    {"netrisk", 1799, "NETRISK"}, 
    {"ansys-lm", 1800, "ANSYS-License manager"}, 
    {"msmq", 1801, "Microsoft Message Que"}, 
    {"concomp1", 1802, "ConComp1"}, 
    {"hp-hcip-gwy", 1803, "HP-HCIP-GWY"}, 
    {"enl", 1804, "ENL"}, 
    {"enl-name", 1805, "ENL-Name"}, 
    {"musiconline", 1806, "Musiconline"}, 
    {"fhsp", 1807, "Fujitsu Hot Standby Protocol"}, 
    {"oracle-vp2", 1808, "Oracle-VP2"}, 
    {"oracle-vp1", 1809, "Oracle-VP1"}, 
    {"jerand-lm", 1810, "Jerand License Manager"}, 
    {"scientia-sdb", 1811, "Scientia-SDB"}, 
    {"radius", 1812, "RADIUS"}, 
    {"radius-acct", 1813, "RADIUS Accounting"}, 
    {"tdp-suite", 1814, "TDP Suite"}, 
    {"mmpft", 1815, "MMPFT"}, 
    {"etftp", 1818, "Enhanced Trivial File Transfer Protocol"}, 
    {"plato-lm", 1819, "Plato License Manager"}, 
    {"mcagent", 1820, "mcagent"}, 
    {"donnyworld", 1821, "donnyworld"}, 
    {"es-elmd", 1822, "es-elmd"}, 
    {"unisys-lm", 1823, "Unisys Natural Language License Manager"}, 
    {"metrics-pas", 1824, "metrics-pas"}, 
    {"fjicl-tep-a", 1901, "Fujitsu ICL Terminal Emulator Program A"}, 
    {"fjicl-tep-b", 1902, "Fujitsu ICL Terminal Emulator Program B"}, 
    {"linkname", 1903, "Local Link Name Resolution"}, 
    {"fjicl-tep-c", 1904, "Fujitsu ICL Terminal Emulator Program C"}, 
    {"sugp", 1905, "Secure UP.Link Gateway Protocol"}, 
    {"tpmd", 1906, "TPortMapperReq"}, 
    {"intrastar", 1907, "IntraSTAR"}, 
    {"dawn", 1908, "Dawn"}, 
    {"global-wlink", 1909, "Global World Link"}, 
    {"mtp", 1911, "Starlight Networks Multimedia Transport Protocol"}, 
    {"mtp", 1911, "Starlight Networks Multimedia Transport Protocol"}, 
    {"armadp", 1913, "armadp"}, 
    {"elm-momentum", 1914, "Elm-Momentum"}, 
    {"facelink", 1915, "FACELINK"}, 
    {"persoft", 1916, "Persoft Persona"}, 
    {"noagent", 1917, "nOAgent"}, 
    {"can-nds", 1918, "Candle Directory Service - NDS"}, 
    {"can-dch", 1919, "Candle Directory Service - DCH"}, 
    {"can-ferret", 1920, "Candle Directory Service - FERRET"}, 
    {"close-combat", 1944, "close-combat"}, 
    {"dialogic-elmd", 1945, "dialogic-elmd"}, 
    {"tekpls", 1946, "tekpls"}, 
    {"hlserver", 1947, "hlserver"}, 
    {"eye2eye", 1948, "eye2eye"}, 
    {"ismaeasdaqlive", 1949, "ISMA Easdaq Live"}, 
    {"ismaeasdaqtest", 1950, "ISMA Easdaq Test"}, 
    {"bcs-lmserver", 1951, "bcs-lmserver"}, 
    {"dlsrap", 1973, "Data Link Switching Remote Access Protocol"}, 
    {"foliocorp", 1985, "Folio Remote Server"}, 
    {"licensedaemon", 1986, "cisco license management"}, 
    {"tr-rsrb-p1", 1987, "cisco RSRB Priority 1 port"}, 
    {"tr-rsrb-p2", 1988, "cisco RSRB Priority 2 port"}, 
    {"tr-rsrb-p3", 1989, "cisco RSRB Priority 3 port"}, 
    {"mshnet", 1989, "MHSnet system"}, 
    {"stun-p1", 1990, "cisco STUN Priority 1 port"}, 
    {"stun-p2", 1991, "cisco STUN Priority 2 port"}, 
    {"stun-p3", 1992, "cisco STUN Priority 3 port"}, 
    {"ipsendmsg", 1992, "IPsendmsg"}, 
    {"snmp-tcp-port", 1993, "cisco SNMP TCP port"}, 
    {"stun-port", 1994, "cisco serial tunnel port"}, 
    {"perf-port", 1995, "cisco perf port"}, 
    {"tr-rsrb-port", 1996, "cisco Remote SRB port"}, 
    {"gdp-port", 1997, "cisco Gateway Discovery Protocol"}, 
    {"x25-svc-port", 1998, "cisco X.25 service (XOT)"}, 
    {"tcp-id-port", 1999, "cisco identification port"}, 
    {"callbook", 2000, "callbook"}, 
    {"dc", 2001, "dc"}, 
    {"globe", 2002, "globe"}, 
    {"mailbox", 2004, "mailbox"}, 
    {"berknet", 2005, "berknet"}, 
    {"invokator", 2006, "invokator"}, 
    {"dectalk", 2007, "dectalk"}, 
    {"conf", 2008, "conf"}, 
    {"news", 2009, "news"}, 
    {"search", 2010, "search"}, 
    {"raid-cc", 2011, "raid"}, 
    {"ttyinfo", 2012, "ttyinfo"}, 
    {"raid-am", 2013, "raid-am"}, 
    {"troff", 2014, "troff"}, 
    {"cypress", 2015, "cypress"}, 
    {"bootserver", 2016, "bootserver"}, 
    {"cypress-stat", 2017, "cypress-stat"}, 
    {"terminaldb", 2018, "terminaldb"}, 
    {"whosockami", 2019, "whosockami"}, 
    {"xinupageserver", 2020, "xinupageserver"}, 
    {"servexec", 2021, "servexec"}, 
    {"down", 2022, "down"}, 
    {"xinuexpansion3", 2023, "xinuexpansion3"}, 
    {"xinuexpansion4", 2024, "xinuexpansion4"}, 
    {"ellpack", 2025, "ell pack"}, 
    {"scrabble", 2026, "scrabble"}, 
    {"shadowserver", 2027, "shadow server"}, 
    {"submitserver", 2028, "submit server"}, 
    {"device2", 2030, "device2"}, 
    {"blackboard", 2032, "blackboard"}, 
    {"glogger", 2033, "glogger"}, 
    {"scoremgr", 2034, "score manager"}, 
    {"imsldoc", 2035, "imsldoc"}, 
    {"objectmanager", 2038, "object manager"}, 
    {"lam", 2040, "lab"}, 
    {"interbase", 2041, "interbase"}, 
    {"isis", 2042, "isis"}, 
    {"isis-bcast", 2043, "isis-bcast"}, 
    {"rimsl", 2044, "rimsl"}, 
    {"cdfunc", 2045, "cdfunc"}, 
    {"sdfunc", 2046, "sdfunc"}, 
    {"dls", 2047, "dls"}, 
    {"dls-monitor", 2048, "dls-monitor"}, 
    {"shilp", 2049, "shilp"}, 
    {"nfs", 2049, "Network File System - Sun Microsystems"}, 
    {"dlsrpn", 2065, "Data Link Switch Read Port Number"}, 
    {"dlswpn", 2067, "Data Link Switch Write Port Number"}, 
    {"zephyr-srv", 2102, "Zephyr server"}, 
    {"zephyr-clt", 2103, "Zephyr serv-hm connection"}, 
    {"zephyr-hm", 2104, "Zephyr hostmanager"}, 
    {"minipay", 2105, "MiniPay"}, 
    {"mc-gt-srv", 2180, "Millicent Vendor Gateway Server"}, 
    {"ats", 2201, "Advanced Training System Program"}, 
    {"imtc-map", 2202, "Int. Multimedia Teleconferencing Cosortium"}, 
    {"kali", 2213, "Kali"}, 
    {"unreg-ab1", 2221, "Allen-Bradley unregistered port"}, 
    {"unreg-ab2", 2222, "Allen-Bradley unregistered port"}, 
    {"inreg-ab3", 2223, "Allen-Bradley unregistered port"}, 
    {"ivs-video", 2232, "IVS Video default"}, 
    {"infocrypt", 2233, "INFOCRYPT"}, 
    {"directplay", 2234, "DirectPlay"}, 
    {"sercomm-wlink", 2235, "Sercomm-WLink"}, 
    {"nani", 2236, "Nani"}, 
    {"optech-port1-lm", 2237, "Optech Port1 License Manager"}, 
    {"aviva-sna", 2238, "AVIVA SNA SERVER"}, 
    {"imagequery", 2239, "Image Query"}, 
    {"ivsd", 2241, "IVS Daemon"}, 
    {"xmquery", 2279, "xmquery"}, 
    {"lnvpoller", 2280, "LNVPOLLER"}, 
    {"lnvconsole", 2281, "LNVCONSOLE"}, 
    {"lnvalarm", 2282, "LNVALARM"}, 
    {"lnvstatus", 2283, "LNVSTATUS"}, 
    {"lnvmaps", 2284, "LNVMAPS"}, 
    {"lnvmailmon", 2285, "LNVMAILMON"}, 
    {"nas-metering", 2286, "NAS-Metering"}, 
    {"dna", 2287, "DNA"}, 
    {"netml", 2288, "NETML"}, 
    {"pehelp", 2307, "pehelp"}, 
    {"sdhelp", 2308, "sdhelp"}, 
    {"cvspserver", 2401, "cvspserver"}, 
    {"rtsserv", 2500, "Resource Tracking system server"}, 
    {"rtsclient", 2501, "Resource Tracking system client"}, 
    {"hp-3000-telnet", 2564, "HP 3000 NS/VT block mode telnet"}, 
    {"netrek", 2592, "netrek"}, 
    {"tqdata", 2700, "tqdata"}, 
    {"www-dev", 2784, "world wide web - development"}, 
    {"aic-np", 2785, "aic-np"}, 
    {"aic-oncrpc", 2786, "aic-oncrpc - Destiny MCD database"}, 
    {"piccolo", 2787, "piccolo - Cornerstone Software"}, 
    {"fryeserv", 2788, "NetWare Loadable Module - Seagate Software"}, 
    {"media-agent", 2789, "Media Agent"}, 
    {"mao", 2908, "mao"}, 
    {"funk-dialout", 2909, "Funk Dialout"}, 
    {"tdaccess", 2910, "TDAccess"}, 
    {"blockade", 2911, "Blockade"}, 
    {"epicon", 2912, "Epicon"}, 
    {"hbci", 3000, "HBCI"}, 
    {"redwood-broker", 3001, "Redwood Broker"}, 
    {"exlm-agent", 3002, "EXLM Agent"}, 
    {"gw", 3010, "Telerate Workstation"}, 
    {"trusted-web", 3011, "Trusted Web"}, 
    {"hlserver", 3047, "Fast Security HL Server"}, 
    {"pctrader", 3048, "Sierra Net PC Trader"}, 
    {"NSWS", 3049, "NSWS"}, 
    {"vmodem", 3141, "VMODEM"}, 
    {"VMOTelnet", 3142, "VMODEM telnet redirect"}, 
    {"rdc-wh-eos", 3142, "RDC WH EOS"}, 
    {"seaview", 3143, "Sea View"}, 
    {"tarantella", 3144, "Tarantella"}, 
    {"csi-lfap", 3145, "CSI-LFAP"}, 
    {"mc-brk-srv", 3180, "Millicent Broker Server"}, 
    {"ccmail", 3264, "cc:mail/lotus"}, 
    {"altav-tunnel", 3265, "Altav Tunnel"}, 
    {"ns-cfg-server", 3266, "NS CFG Server"}, 
    {"ibm-dial-out", 3267, "IBM Dial Out"}, 
    {"msft-gc", 3268, "Microsoft Global Catalog"}, 
    {"msft-gc-ssl", 3269, "Microsoft Global Catalog with LDAP/SSL"}, 
    {"verismart", 3270, "Verismart"}, 
    {"csoft-prev", 3271, "CSoft Prev Port"}, 
    {"user-manager", 3272, "Fujitsu User Manager"}, 
    {"sxmp", 3273, "Simple Experimental Multiplexed Protocol"}, 
    {"ordinox-server", 3274, "Ordinox Server"}, 
    {"samd", 3275, "SAMD"}, 
    {"maxim-asics", 3276, "Maxim ASICs"}, 
    {"dec-notes", 3333, "DEC Notes"}, 
    {"eggdrop", 3333, "Common for eggdrop bot"}, 
    {"bmap", 3421, "Bull Apprise portmapper"}, 
    {"mira", 3454, "Apple Remote Access Protocol"}, 
    {"prsvp", 3455, "RSVP Port"}, 
    {"vat", 3456, "VAT default data"}, 
    {"vat-control", 3457, "VAT default control"}, 
    {"d3winosfi", 3458, "D3WinOsfi"}, 
    {"integral", 3459, "Integral"}, 
    {"udt_os", 3900, "Unidata UDT OS"}, 
    {"mapper-nodemgr", 3984, "MAPPER network node manager"}, 
    {"mapper-mapethd", 3985, "MAPPER TCP/IP server"}, 
    {"mapper-ws_ethd", 3986, "MAPPER workstation server"}, 
    {"terabase", 4000, "Terabase"}, 
    {"netcheque", 4008, "NetCheque accounting"}, 
    {"chimera-hwm", 4009, "Chimera HWM"}, 
    {"samsung-unidex", 4010, "Samsung Unidex"}, 
    {"altserviceboot", 4011, "Alternate Service Boot"}, 
    {"pda-gate", 4012, "PDA Gate"}, 
    {"acl-manager", 4013, "ACL Manager"}, 
    {"nuts_dem", 4132, "NUTS Daemon"}, 
    {"nuts_bootp", 4133, "NUTS Bootp Server"}, 
    {"nifty-hmi", 4134, "NIFTY-Serve HMI protocol"}, 
    {"oirtgsvc", 4141, "Workflow Server"}, 
    {"oidocsvc", 4142, "Document Server"}, 
    {"oidsr", 4143, "Document Replication"}, 
    {"rwhois", 4321, "Remote Who Is"}, 
    {"unicall", 4343, "UNICALL"}, 
    {"vinainstall", 4344, "VinaInstall"}, 
    {"krb524", 4444, "KRB524"}, 
    {"nv-video", 4444, "NV Video default"}, 
    {"eggdrop", 4444, "Common for eggdrop bot"}, 
    {"upnotifyp", 4445, "UPNOTIFYP"}, 
    {"n1-fwp", 4446, "N1-FWP"}, 
    {"n1-rmgmt", 4447, "N1-RMGMT"}, 
    {"asc-slmd", 4448, "ASC Licence Manager"}, 
    {"arcryptoip", 4449, "ARCrypto IP"}, 
    {"camp", 4450, "Camp"}, 
    {"ctisystemmsg", 4451, "CTI System Msg"}, 
    {"ctiprogramload", 4452, "CTI Program Load"}, 
    {"nssalertmgr", 4453, "NSS Alert Manager"}, 
    {"nssagentmgr", 4454, "NSS Agent Manager"}, 
    {"sae-urn", 4500, "sae-urn"}, 
    {"urn-x-cdchoice", 4501, "urn-x-cdchoice"}, 
    {"rfa", 4672, "remote file access server"}, 
    {"commplex-main", 5000, "Complex Main"}, 
    {"commplex-link", 5001, "Complex Link"}, 
    {"rfe", 5002, "radio free ethernet"}, 
    {"claris-fmpro", 5003, "Claris FileMaker Pro"}, 
    {"avt-profile-1", 5004, "avt-profile-1"}, 
    {"avt-profile-2", 5005, "avt-profile-2"}, 
    {"telelpathstart", 5010, "TelepathStart"}, 
    {"telelpathattack", 5011, "TelepathAttack"}, 
    {"zenginkyo-1", 5020, "zenginkyo-1"}, 
    {"zenginkyo-2", 5021, "zenginkyo-2"}, 
    {"mmcc", 5050, "multimedia conference control tool"}, 
    {"rmonitor_secure", 5145, "rmonitor secure"}, 
    {"atmp", 5150, "Ascend Tunnel Management Protocol"}, 
    {"aol", 5190, "America-Online"}, 
    {"aol-1", 5191, "AmericaOnline1"}, 
    {"aol-2", 5192, "AmericaOnline2"}, 
    {"aol-3", 5193, "AmericaOnline3"}, 
    {"padl2sim", 5236, "padl2sim"}, 
    {"hacl-hb", 5300, "HA cluster heartbeat"}, 
    {"hacl-gs", 5301, "HA cluster general services"}, 
    {"hacl-cfg", 5302, "HA cluster configuration"}, 
    {"hacl-probe", 5303, "HA cluster probing"}, 
    {"hacl-local", 5304, "HA Cluster Commands"}, 
    {"hacl-test", 5305, "HA Cluster Test"}, 
    {"sun-mc-grp", 5306, "Sun MC Group"}, 
    {"sco-aip", 5307, "SCO AIP"}, 
    {"cfengine", 5308, "CFengine"}, 
    {"jprinter", 5309, "J Printer"}, 
    {"outlaws", 5310, "Outlaws"}, 
    {"tmlogin", 5311, "TM Login"}, 
    {"excerpt", 5400, "Excerpt Search"}, 
    {"excerpts", 5401, "Excerpt Search Secure"}, 
    {"mftp", 5402, "MFTP"}, 
    {"hpoms-ci-lstn", 5403, "HPOMS-CI-LSTN"}, 
    {"hpoms-dps-lstn", 5404, "HPOMS-DPS-LSTN"}, 
    {"netsupport", 5405, "NetSupport"}, 
    {"systemics-sox", 5406, "Systemics Sox"}, 
    {"foresyte-clear", 5407, "Foresyte-Clear"}, 
    {"foresyte-sec", 5408, "Foresyte-Sec"}, 
    {"salient-dtasrv", 5409, "Salient Data Server"}, 
    {"salient-usrmgr", 5410, "Salient User Manager"}, 
    {"actnet", 5411, "ActNet"}, 
    {"continuus", 5412, "Continuus"}, 
    {"wwiotalk", 5413, "WWIOTALK"}, 
    {"statusd", 5414, "StatusD"}, 
    {"ns-server", 5415, "NS Server"}, 
    {"sns-gateway", 5416, "SNS Gateway"}, 
    {"sns-agent", 5417, "SNS Agent"}, 
    {"mcntp", 5418, "MCNTP"}, 
    {"dj-ice", 5419, "DJ-ICE"}, 
    {"cylink-c", 5420, "Cylink-C"}, 
    {"personal-agent", 5555, "Personal Agent"}, 
    {"eggdrop", 5555, "Common for eggdrop bot"}, 
    {"esmmanager", 5600, "Enterprise Security Manager"}, 
    {"esmagent", 5601, "Enterprise Security Agent"}, 
    {"a1-msc", 5602, "A1-MSC"}, 
    {"a1-bs", 5603, "A1-BS"}, 
    {"a3-sdunode", 5604, "A3-SDUNode"}, 
    {"a4-sdunode", 5605, "A4-SDUNode"}, 
    {"pcanywheredata", 5631, "pcANYWHEREdata"}, 
    {"pcanywherestat", 5632, "pcANYWHEREstat"}, 
    {"rrac", 5678, "Remote Replication Agent Connection"}, 
    {"dccm", 5679, "Direct Cable Connect Manager"}, 
    {"proshareaudio", 5713, "proshare conf audio"}, 
    {"prosharevideo", 5714, "proshare conf video"}, 
    {"prosharedata", 5715, "proshare conf data"}, 
    {"prosharerequest", 5716, "proshare conf request"}, 
    {"prosharenotify", 5717, "proshare conf notify"}, 
    {"openmail", 5729, "Openmail User Agent Layer"}, 
    {"fcopy-server", 5745, "fcopy-server"}, 
    {"openmailg", 5755, "OpenMail Desk Gateway server"}, 
    {"x500ms", 5757, "OpenMail X.500 Directory Server"}, 
    {"openmailns", 5766, "OpenMail NewMail Server"}, 
    {"s-openmail", 5767, "OpenMail Suer Agent Layer (Secure)"}, 
    {"x11", 6000, "X Window System"}, 
    {"x11", 6001, "X Window System"}, 
    {"x11", 6002, "X Window System"}, 
    {"x11", 6003, "X Window System"}, 
    {"x11", 6004, "X Window System"}, 
    {"x11", 6005, "X Window System"}, 
    {"x11", 6006, "X Window System"}, 
    {"x11", 6007, "X Window System"}, 
    {"x11", 6008, "X Window System"}, 
    {"x11", 6009, "X Window System"}, 
    {"x11", 6010, "X Window System"}, 
    {"x11", 6011, "X Window System"}, 
    {"x11", 6012, "X Window System"}, 
    {"x11", 6013, "X Window System"}, 
    {"x11", 6014, "X Window System"}, 
    {"x11", 6015, "X Window System"}, 
    {"x11", 6016, "X Window System"}, 
    {"x11", 6017, "X Window System"}, 
    {"x11", 6018, "X Window System"}, 
    {"x11", 6019, "X Window System"}, 
    {"x11", 6020, "X Window System"}, 
    {"x11", 6021, "X Window System"}, 
    {"x11", 6022, "X Window System"}, 
    {"x11", 6023, "X Window System"}, 
    {"x11", 6024, "X Window System"}, 
    {"x11", 6025, "X Window System"}, 
    {"x11", 6026, "X Window System"}, 
    {"x11", 6027, "X Window System"}, 
    {"x11", 6028, "X Window System"}, 
    {"x11", 6029, "X Window System"}, 
    {"x11", 6030, "X Window System"}, 
    {"x11", 6031, "X Window System"}, 
    {"x11", 6032, "X Window System"}, 
    {"x11", 6033, "X Window System"}, 
    {"x11", 6034, "X Window System"},
    {"x11", 6035, "X Window System"}, 
    {"x11", 6036, "X Window System"}, 
    {"x11", 6037, "X Window System"}, 
    {"x11", 6038, "X Window System"}, 
    {"x11", 6039, "X Window System"}, 
    {"x11", 6040, "X Window System"}, 
    {"x11", 6041, "X Window System"}, 
    {"x11", 6042, "X Window System"}, 
    {"x11", 6043, "X Window System"}, 
    {"x11", 6044, "X Window System"}, 
    {"x11", 6045, "X Window System"}, 
    {"x11", 6046, "X Window System"}, 
    {"x11", 6047, "X Window System"}, 
    {"x11", 6048, "X Window System"}, 
    {"x11", 6049, "X Window System"}, 
    {"x11", 6050, "X Window System"}, 
    {"x11", 6051, "X Window System"}, 
    {"x11", 6052, "X Window System"}, 
    {"x11", 6053, "X Window System"}, 
    {"x11", 6054, "X Window System"}, 
    {"x11", 6055, "X Window System"}, 
    {"x11", 6056, "X Window System"}, 
    {"x11", 6057, "X Window System"}, 
    {"x11", 6058, "X Window System"}, 
    {"x11", 6059, "X Window System"}, 
    {"x11", 6060, "X Window System"}, 
    {"x11", 6061, "X Window System"},
    {"x11", 6062, "X Window System"}, 
    {"x11", 6063, "X Window System"}, 
    {"softcm", 6110, "HP SoftBench CM"}, 
    {"spc", 6111, "HP SoftBench Sub-Process Control"}, 
    {"dtspcd", 6112, "dtspcd"}, 
    {"backup-express", 6123, "Backup Express"}, 
    {"meta-corp", 6141, "Meta Corporation License Manager"}, 
    {"aspentec-lm", 6142, "Aspen Technology License Manager"}, 
    {"watershed-lm", 6143, "Watershed License Manager"}, 
    {"statsci1-lm", 6144, "StatSci License Manager - 1"}, 
    {"statsci2-lm", 6145, "StatSci License Manager - 2"}, 
    {"lonewolf-lm", 6146, "Lone Wolf Systems License Manager"}, 
    {"montage-lm", 6147, "Montage License Manager"}, 
    {"ricardo-lm", 6148, "Ricardo North America License Manager"}, 
    {"tal-pod", 6149, "tal-pod"}, 
    {"crip", 6253, "CRIP"}, 
    {"clariion-evr01", 6389, "clariion-evr01"}, 
    {"skip-cert-recv", 6455, "SKIP Certificate Receive"}, 
    {"skip-cert-send", 6456, "SKIP Certificate Send"}, 
    {"lvision-lm", 6471, "LVision License Manager"}, 
    {"xdsxdm", 6558, "xdsxdm"}, 
    {"circ", 6660, "Common for IRCD"}, 
    {"circ", 6661, "Common for IRCD"}, 
    {"circ", 6662, "Common for IRCD"}, 
    {"circ", 6663, "Common for IRCD"}, 
    {"circ", 6664, "Common for IRCD"}, 
    {"circ", 6665, "Common for IRCD"},
    {"circ", 6666, "Common for IRCD"}, 
    {"nirc", 6667, "Normal for IRCD/backbone"}, 
    {"circ", 6668, "Common for IRCD"}, 
    {"circ", 6669, "Common for IRCD"}, 
    {"vocaltec-gold", 6670, "Vocaltec Global Online Directory"}, 
    {"circ", 6670, "Common for IRCD"}, 
    {"vision_server", 6672, "vision_server"}, 
    {"vision_elmd", 6673, "vision_elmd"}, 
    {"ambit-lm", 6831, "ambit-lm"}, 
    {"acmsoda", 6969, "acmsoda"}, 
    {"afs3-fileserver", 7000, "file server itself"}, 
    {"afs3-callback", 7001, "callbacks to cache managers"}, 
    {"afs3-prserver", 7002, "users & groups database"}, 
    {"afs3-vlserver", 7003, "volume location database"}, 
    {"afs3-kaserver", 7004, "AFS/Kerberos authentication service"}, 
    {"afs3-volser", 7005, "volume managment server"}, 
    {"afs3-errors", 7006, "error interpretation service"}, 
    {"afs3-bos", 7007, "basic overseer process"}, 
    {"afs3-update", 7008, "server-to-server updater"}, 
    {"afs3-rmtsys", 7009, "remote cache manager service"}, 
    {"ups-onlinet", 7010, "onlinet uninterruptable power supplies"}, 
    {"lazy-ptop", 7099, "lazy-ptop"}, 
    {"font-service", 7100, "X Font Service"}, 
    {"virprot-lm", 7121, "Virtual Prototypes License Manager"}, 
    {"virprot-lm", 7121, "Virtual Prototypes License Manager"}, 
    {"clutild", 7174, "Clutild"}, 
    {"clutild", 7174, "Clutild"},
    {"fodms", 7200, "FODMS FLIP"}, 
    {"dlip", 7201, "DLIP"}, 
    {"winqedit", 7395, "winqedit"}, 
    {"pmdmgr", 7426, "OpenView DM Postmaster Manager"}, 
    {"oveadmgr", 7427, "OpenView DM Event Agent Manager"}, 
    {"ovladmgr", 7428, "OpenView DM Log Agent Manager"}, 
    {"opi-sock", 7429, "OpenView DM rqt communication"}, 
    {"xmpv7", 7430, "OpenView DM xmpv7 api pipe"}, 
    {"pmd", 7431, "OpenView DM ovc/xmpv3 api pipe"}, 
    {"telops-lmd", 7491, "telops-lmd"}, 
    {"pafec-lm", 7511, "pafec-lm"}, 
    {"cbt", 7777, "cbt"}, 
    {"eggdrop", 7777, "Common for eggdrop bot"}, 
    {"accu-lmgr", 7781, "accu-lmgr"}, 
    {"quest-vista", 7980, "Quest Vista"}, 
    {"irdmi2", 7999, "iRDMI2"}, 
    {"irdmi", 8000, "iRDMI"}, 
    {"pro-ed", 8032, "ProEd"}, 
    {"npmp", 8450, "npmp"}, 
    {"ddi-tcp-1", 8888, "NewsEDGE server TCP (TCP 1)"}, 
    {"ddi-tcp-2", 8889, "Desktop Data TCP 1"}, 
    {"ddi-tcp-3", 8890, "Desktop Data TCP 2"}, 
    {"ddi-tcp-4", 8891, "Desktop Data TCP 3: NESS application"}, 
    {"ddi-tcp-5", 8892, "Desktop Data TCP 4: FARM product"}, 
    {"ddi-tcp-6", 8893, "Desktop Data TCP 5: NewsEDGE/Web application"}, 
    {"ddi-tcp-7", 8894, "Desktop Data TCP 6: COAL application"}, 
    {"cslistener", 9000, "CSlistener"},
    {"man", 9535, "man"}, 
    {"sd", 9876, "Session Director"}, 
    {"palace", 9992, "Palace"}, 
    {"palace", 9993, "Palace"}, 
    {"palace", 9994, "Palace"}, 
    {"palace", 9995, "Palace"}, 
    {"palace", 9996, "Palace"}, 
    {"palace", 9997, "Palace"}, 
    {"distinct32", 9998, "Distinct32"}, 
    {"pirc", 9998, "Possible for IRCD"}, 
    {"distinct", 9999, "distinct"}, 
    {"ndmp", 10000, "Network Data Management Protocol"}, 
    {"tsaf", 12753, "tsaf port"}, 
    {"dsmcc-config", 13818, "DSMCC Config"}, 
    {"dsmcc-session", 13819, "DSMCC Session Messages"}, 
    {"dsmcc-passthru", 13820, "DSMCC Pass-Thru Messages"}, 
    {"dsmcc-download", 13821, "DSMCC Download Protocol"}, 
    {"dsmcc-ccp", 13822, "DSMCC Channel Change Protocol"}, 
    {"isode-dua", 17007, "isode-dua"}, 
    {"biimenu", 18000, "Beckman Instruments, Inc."},
    {"webphone", 21845, "webphone"},
    {"netspeak-is", 21846, "NetSpeak Corp. Directory Services"}, 
    {"netspeak-cs", 21847, "NetSpeak Corp. Connection Services"}, 
    {"netspeak-acd", 21848, "NetSpeak Corp. Automatic Call Distribution"}, 
    {"netspeak-cps", 21849, "NetSpeak Corp. Credit Processing System"}, 
    {"wnn6", 22273, "wnn6"}, 
    {"vocaltec-wconf", 22555, "Vocaltec Web Conference"},
    {"aws-brf", 22800, "Telerate Information Platform LAN"}, 
    {"brf-gw", 22951, "Telerate Information Platform WAN"}, 
    {"icl-twobase1", 25000, "icl-twobase1"}, 
    {"icl-twobase2", 25001, "icl-twobase2"}, 
    {"icl-twobase3", 25002, "icl-twobase3"}, 
    {"icl-twobase4", 25003, "icl-twobase4"},
    {"icl-twobase5", 25004, "icl-twobase5"},
    {"icl-twobase6", 25005, "icl-twobase6"},
    {"icl-twobase7", 25006, "icl-twobase7"},
    {"icl-twobase8", 25007, "icl-twobase8"},
    {"icl-twobase9", 25008, "icl-twobase9"},
    {"icl-twobase10", 25009, "icl-twobase10"},
    {"vocaltec-hos", 25793, "Vocaltec Address Server"}, 
    {"quake", 26000, "quake"}, 
    {"wnn6-ds", 26208, "wnn6-ds"}, 
    {"pirc", 31337, "Possible for IRCD"}, 
    {"dbbrowse", 47557, "Databeam Corporation"}, 
    {"ap", 47806, "ALC Protocol"}, 
    {"bacnet", 47808, "Building Automation and Control Networks"}, 
    {"HIPORT", 65535, "up port telnet"}
  };





int RFC1060portscount = sizeof(RFC1060ports) / sizeof(RFC1060ports[0]);
