//---------------------------------------------------------------------------
#ifndef rpcthreadDLLH
#define rpcthreadDLLH
//---------------------------------------------------------------------------
#include <Classes.hpp>
//---------------------------------------------------------------------------

// problem with definition of __try - this gets round out with no problems
#define __try try

#include "winampinterface.h"    // header file generated by MIDL compiler

enum WAExecutionStatus {waServerStarting, waServerStarted, waListening, waExecuting, waServerStopped, waInitialiseFailed};

class TRPCServerThread : public TThread
{
private:
protected:
    void __fastcall Execute();
public:
    __fastcall TRPCServerThread(bool CreateSuspended);
    AnsiString Endpoint;
};


  void __fastcall MainMessage(char * msgString);
  void __fastcall MainStatus(WAExecutionStatus Status);
  void __fastcall MainIdent(char * msgString);

/*the actual RPC interface procedures*/

void WAMessageProc(
    /* [string][out][in] */ unsigned char __RPC_FAR *pszString);

void WAExecuteMessage(
    /* [string][in] */ unsigned char __RPC_FAR *pszString,
    /* [in] */ int command);

void WAExecuteMessageString(
    /* [string][in] */ unsigned char __RPC_FAR *pszString,
    /* [string][in] */ unsigned char __RPC_FAR *pszParam,
    /* [in] */ int command);

int WAIntegerResult(
    /* [string][in] */ unsigned char __RPC_FAR *pszString,
    int command,
    int data);

int WAStringResult(
    /* [size_is][string][out][in] */ unsigned char __RPC_FAR *pszString,
    int command,
    int data);

void WAShutdown( void);


//---------------------------------------------------------------------------
#endif
