// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*DFMFileType*/ /*AboutF.dfm*/
/*ITE*/ /*DFMFileType*/ /*ConfigDLLF.dfm*/
/*ITE*/ /*DFMFileType*/ /*DetailsF.dfm*/
/*ITE*/ /*DFMFileType*/ /*ServerDLLF.dfm*/
/*ITE*/ /*RCFileType*/ /*gen_RPCinterface_DRC.rc*/
//---------------------------------------------------------------------------
USEFORMRES("AboutF.dfm", frmAbout, Form); /* TForm: DesignClass */
USEFORMRES("ConfigDLLF.dfm", ConfigForm, Form); /* TForm: DesignClass */
USEFORMRES("DetailsF.dfm", frmDetails, Form); /* TForm: DesignClass */
USEFORMRES("ServerDLLF.dfm", frmMain, Form); /* TForm: DesignClass */
USERC("gen_RPCinterface_DRC.rc");
USERES("gen_RPCinterface.res");
//---------------------------------------------------------------------------
#define DllEntryPoint
