// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*DFMFileType*/ /*AboutF.dfm*/
/*ITE*/ /*DFMFileType*/ /*CommandF.dfm*/
/*ITE*/ /*DFMFileType*/ /*DetailsF.dfm*/
/*ITE*/ /*DFMFileType*/ /*MainF.dfm*/
/*ITE*/ /*DFMFileType*/ /*messageF.dfm*/
/*ITE*/ /*DFMFileType*/ /*PlaylistF.dfm*/
/*ITE*/ /*DFMFileType*/ /*ServersF.dfm*/
/*ITE*/ /*DFMFileType*/ /*SettingsF.dfm*/
/*ITE*/ /*DFMFileType*/ /*SplashF.dfm*/
/*ITE*/ /*RCFileType*/ /*remote_DRC.rc*/
//---------------------------------------------------------------------------
USEFORMRES("AboutF.dfm", frmAbout, Form); /* TForm: DesignClass */
USEFORMRES("CommandF.dfm", frmCommands, Form); /* TForm: DesignClass */
USEFORMRES("DetailsF.dfm", frmDetails, Form); /* TForm: DesignClass */
USEFORMRES("MainF.dfm", frmMain, Form); /* TForm: DesignClass */
USEFORMRES("messageF.dfm", frmMessage, Form); /* TForm: DesignClass */
USEFORMRES("PlaylistF.dfm", frmPlaylist, Form); /* TForm: DesignClass */
USEFORMRES("ServersF.dfm", frmServers, Form); /* TForm: DesignClass */
USEFORMRES("SettingsF.dfm", frmSettings, Form); /* TForm: DesignClass */
USEFORMRES("SplashF.dfm", frmSplash, Form); /* TForm: DesignClass */
USERC("remote_DRC.rc");
USERES("remote.res");
//---------------------------------------------------------------------------
#define DllEntryPoint
