var annotated =
[
    [ "Catch", null, null ],
    [ "std", null, null ],
    [ "WinampRemote", "namespace_winamp_remote.html", "namespace_winamp_remote" ],
    [ "__MIDL_winamp_0001", "struct_____m_i_d_l__winamp__0001.html", "struct_____m_i_d_l__winamp__0001" ],
    [ "_MIDL_PROC_FORMAT_STRING", "struct___m_i_d_l___p_r_o_c___f_o_r_m_a_t___s_t_r_i_n_g.html", "struct___m_i_d_l___p_r_o_c___f_o_r_m_a_t___s_t_r_i_n_g" ],
    [ "_MIDL_TYPE_FORMAT_STRING", "struct___m_i_d_l___t_y_p_e___f_o_r_m_a_t___s_t_r_i_n_g.html", "struct___m_i_d_l___t_y_p_e___f_o_r_m_a_t___s_t_r_i_n_g" ],
    [ "DefaultCallObserver", "class_default_call_observer.html", "class_default_call_observer" ],
    [ "EIPException", "class_e_i_p_exception.html", "class_e_i_p_exception" ],
    [ "ERPCException", "class_e_r_p_c_exception.html", "class_e_r_p_c_exception" ],
    [ "GlassExtender", "class_glass_extender.html", "class_glass_extender" ],
    [ "NetworkTest", "class_network_test.html", "class_network_test" ],
    [ "porttype", "structporttype.html", "structporttype" ],
    [ "ServerEnumerator", "class_server_enumerator.html", "class_server_enumerator" ],
    [ "ServerInfo", "struct_server_info.html", "struct_server_info" ],
    [ "ServerTester", "class_server_tester.html", "class_server_tester" ],
    [ "TConfigForm", "class_t_config_form.html", "class_t_config_form" ],
    [ "TfrmAbout", "class_tfrm_about.html", "class_tfrm_about" ],
    [ "TfrmCommands", "class_tfrm_commands.html", "class_tfrm_commands" ],
    [ "TfrmDetails", "class_tfrm_details.html", "class_tfrm_details" ],
    [ "TfrmMain", "class_tfrm_main.html", "class_tfrm_main" ],
    [ "TfrmMessage", "class_tfrm_message.html", "class_tfrm_message" ],
    [ "TfrmPlaylist", "class_tfrm_playlist.html", "class_tfrm_playlist" ],
    [ "TfrmPluginMain", "class_tfrm_plugin_main.html", "class_tfrm_plugin_main" ],
    [ "TfrmServers", "class_tfrm_servers.html", "class_tfrm_servers" ],
    [ "TfrmSettings", "class_tfrm_settings.html", "class_tfrm_settings" ],
    [ "TfrmSplash", "class_tfrm_splash.html", "class_tfrm_splash" ],
    [ "TModuleVersionInfo", "class_t_module_version_info.html", "class_t_module_version_info" ],
    [ "TRPCServerDLLThread", "class_t_r_p_c_server_d_l_l_thread.html", "class_t_r_p_c_server_d_l_l_thread" ],
    [ "TRPCServerThread", "class_t_r_p_c_server_thread.html", "class_t_r_p_c_server_thread" ],
    [ "winamp", "interfacewinamp.html", "interfacewinamp" ],
    [ "winampGeneralPurposePlugin", "structwinamp_general_purpose_plugin.html", "structwinamp_general_purpose_plugin" ]
];