The Winamp Remote Control suite: TdmRemote Class Reference
TdmRemote Class Reference
#include <remoteDM.h>
Public Member Functions
void __fastcall PauseExecute (TObject *Sender)
void __fastcall PlayExecute (TObject *Sender)
void __fastcall NextExecute (TObject *Sender)
void __fastcall NextFadeExecute (TObject *Sender)
void __fastcall PreviousExecute (TObject *Sender)
void __fastcall StopExecute (TObject *Sender)
void __fastcall Forward5Execute (TObject *Sender)
void __fastcall Back5Execute (TObject *Sender)
void __fastcall VolumeUpExecute (TObject *Sender)
void __fastcall VolumeDownExecute (TObject *Sender)
void __fastcall VolumeUpMoreExecute (TObject *Sender)
void __fastcall VolumeDownMoreExecute (TObject *Sender)
void __fastcall PlaylistStartExecute (TObject *Sender)
void __fastcall PlaylistEndExecute (TObject *Sender)
void __fastcall DeletePlayListExecute (TObject *Sender)
void __fastcall StopFadeExecute (TObject *Sender)
void __fastcall StopAfterCurrentExecute (TObject *Sender)
void __fastcall SetVolume0Execute (TObject *Sender)
void __fastcall SetVolume100Execute (TObject *Sender)
void __fastcall ShuffleExecute (TObject *Sender)
void __fastcall RepeatExecute (TObject *Sender)
void __fastcall PlayFromStartExecute (TObject *Sender)
void __fastcall HalfExecute (TObject *Sender)
void __fastcall ViewToolBarExecute (TObject *Sender)
void __fastcall ViewPlaylistExecute (TObject *Sender)
void __fastcall ViewVolumeExecute (TObject *Sender)
void __fastcall AutoloadExecute (TObject *Sender)
void __fastcall EQOnExecute (TObject *Sender)
void __fastcall DetailsExecute (TObject *Sender)
void __fastcall PreviousFadeExecute (TObject *Sender)
void __fastcall SongChangingExecute (TObject *Sender)
void __fastcall SongChangedExecute (TObject *Sender)
void __fastcall NewSongExecute (TObject *Sender)
void __fastcall PlaylistRefreshExecute (TObject *Sender)
void __fastcall PlaylistRefreshStatsExecute (TObject *Sender)
void __fastcall AboutExecute (TObject *Sender)
void __fastcall AddDirectoryExecute (TObject *Sender)
void __fastcall AddPlayIistExecute (TObject *Sender)
void __fastcall DownExecute (TObject *Sender)
void __fastcall DownMoreExecute (TObject *Sender)
void __fastcall EndExecute (TObject *Sender)
void __fastcall FullExecute (TObject *Sender)
void __fastcall LocateServersExecute (TObject *Sender)
void __fastcall PlaceOnTrayExecute (TObject *Sender)
void __fastcall PlaylistRefreshCurrentExecute (TObject *Sender)
void __fastcall ShowMainFormExecute (TObject *Sender)
void __fastcall StartExecute (TObject *Sender)
void __fastcall UpExecute (TObject *Sender)
void __fastcall UpMoreExecute (TObject *Sender)
void __fastcall ZeroExecute (TObject *Sender)
void __fastcall DataModuleCreate (TObject *Sender)
void __fastcall DataModuleDestroy (TObject *Sender)
void __fastcall ExitExecute (TObject *Sender)
void __fastcall HideOnStartExecute (TObject *Sender)
void __fastcall RestoreOnStartExecute (TObject *Sender)
void __fastcall ChangeFadeExecute (TObject *Sender)
__fastcall TdmRemote (TComponent *Owner)
void setClient (WinampRemote::Client::IWinamp *client_)
void __fastcall DropFiles (TStringList *DropFiles, int DropIndex)
void __fastcall DoAddFiles (TStrings *Files, int selectedIndex=-1)
void __fastcall PlaylistDragDrop (int dropIndex, int currentPos)
void __fastcall SetSongPosition (int pos, int width)
void __fastcall SetVolume (int volume)
void __fastcall SetBalance (int balance)
void __fastcall BarChange (int index, byte position)
void __fastcall UpdateBars ()
void __fastcall UpdateValues ()
WAPlaybackStatus __fastcall PlaybackStatus ()
std::string __fastcall WinampVersionString ()
std::string __fastcall CurrentSong ()
void __fastcall GetPlaylistState (int &length, int &index)
void __fastcall DoDeleteSelected (void)
void __fastcall DoBind (const AnsiString &address, const AnsiString &endpoint)
void __fastcall registerForm (TForm *aForm)
void __fastcall unRegisterForm (TForm *aForm)
Public Attributes
TActionList * alMain
TAction * PlaceOnTray
TAction * Exit
TAction * ViewToolBar
TAction * Pause
TAction * Play
TAction * Stop
TAction * StopFade
TAction * StopAfterCurrent
TAction * Forward5
TAction * Back5
TAction * ViewPlaylist
TAction * Shuffle
TAction * Repeat
TAction * Next
TAction * Previous
TAction * Start
TAction * End
TAction * PlaylistRefresh
TAction * PlayFromStart
TAction * AddPlayIist
TAction * AddDirectory
TAction * ViewVolume
TAction * Up
TAction * Down
TAction * UpMore
TAction * DownMore
TAction * Zero
TAction * Half
TAction * Full
TAction * About
TAction * ShowMainForm
TAction * LocateServers
TAction * Autoload
TAction * Details
TAction * NextFade
TAction * PreviousFade
TAction * SongChanging
TAction * SongChanged
TAction * NewSong
TAction * PlaylistRefreshCurrent
TAction * PlaylistRefreshStats
TAction * EQOn
TOpenDialog * odlgMain
TAction * HideOnStart
TAction * RestoreOnStart
TAction * ChangeFade
Detailed Description
Definition at line 26 of file remoteDM.h.
Constructor & Destructor Documentation
__fastcall TdmRemote::TdmRemote (TComponent * Owner)
Definition at line 21 of file remoteDM.cpp.
Member Function Documentation
void __fastcall TdmRemote::AboutExecute (TObject * Sender)
Definition at line 430 of file remoteDM.cpp.
void __fastcall TdmRemote::AddDirectoryExecute (TObject * Sender)
Definition at line 453 of file remoteDM.cpp.
void __fastcall TdmRemote::AddPlayIistExecute (TObject * Sender)
Definition at line 457 of file remoteDM.cpp.
void __fastcall TdmRemote::AutoloadExecute (TObject * Sender)
Definition at line 302 of file remoteDM.cpp.
void __fastcall TdmRemote::Back5Execute (TObject * Sender)
Definition at line 168 of file remoteDM.cpp.
void __fastcall TdmRemote::BarChange (int index, byte position)
Definition at line 678 of file remoteDM.cpp.
Referenced by TfrmSettings::BarsChange().
void __fastcall TdmRemote::ChangeFadeExecute (TObject * Sender)
Definition at line 845 of file remoteDM.cpp.
std::string __fastcall TdmRemote::CurrentSong ()
Definition at line 728 of file remoteDM.cpp.
Referenced by PlaylistDragDrop().
void __fastcall TdmRemote::DataModuleCreate (TObject * Sender)
Definition at line 776 of file remoteDM.cpp.
void __fastcall TdmRemote::DataModuleDestroy (TObject * Sender)
Definition at line 781 of file remoteDM.cpp.
void __fastcall TdmRemote::DeletePlayListExecute (TObject * Sender)
Definition at line 211 of file remoteDM.cpp.
void __fastcall TdmRemote::DetailsExecute (TObject * Sender)
Definition at line 316 of file remoteDM.cpp.
void __fastcall TdmRemote::DoAddFiles (TStrings * Files, int selectedIndex = -1)
Definition at line 80 of file remoteDM.cpp.
Referenced by AddPlayIistExecute(), DoDeleteSelected(), DropFiles(), and PlaylistDragDrop().
void __fastcall TdmRemote::DoBind (const AnsiString & address, const AnsiString & endpoint)
Definition at line 120 of file remoteDM.cpp.
Referenced by TfrmMain::FormCreate(), and LocateServersExecute().
void __fastcall TdmRemote::DoDeleteSelected (void)
Definition at line 744 of file remoteDM.cpp.
void __fastcall TdmRemote::DownExecute (TObject * Sender)
Definition at line 484 of file remoteDM.cpp.
void __fastcall TdmRemote::DownMoreExecute (TObject * Sender)
Definition at line 489 of file remoteDM.cpp.
void __fastcall TdmRemote::DropFiles (TStringList * DropFiles, int DropIndex)
Definition at line 93 of file remoteDM.cpp.
void __fastcall TdmRemote::EndExecute (TObject * Sender)
Definition at line 494 of file remoteDM.cpp.
void __fastcall TdmRemote::EQOnExecute (TObject * Sender)
Definition at line 308 of file remoteDM.cpp.
void __fastcall TdmRemote::ExitExecute (TObject * Sender)
Definition at line 499 of file remoteDM.cpp.
void __fastcall TdmRemote::Forward5Execute (TObject * Sender)
Definition at line 163 of file remoteDM.cpp.
void __fastcall TdmRemote::FullExecute (TObject * Sender)
Definition at line 276 of file remoteDM.cpp.
void __fastcall TdmRemote::GetPlaylistState (int & length, int & index)
Definition at line 738 of file remoteDM.cpp.
void __fastcall TdmRemote::HalfExecute (TObject * Sender)
Definition at line 270 of file remoteDM.cpp.
void __fastcall TdmRemote::HideOnStartExecute (TObject * Sender)
Definition at line 833 of file remoteDM.cpp.
void __fastcall TdmRemote::LocateServersExecute (TObject * Sender)
Definition at line 504 of file remoteDM.cpp.
void __fastcall TdmRemote::NewSongExecute (TObject * Sender)
Definition at line 353 of file remoteDM.cpp.
void __fastcall TdmRemote::NextExecute (TObject * Sender)
Definition at line 136 of file remoteDM.cpp.
void __fastcall TdmRemote::NextFadeExecute (TObject * Sender)
Definition at line 143 of file remoteDM.cpp.
void __fastcall TdmRemote::PauseExecute (TObject * Sender)
Definition at line 125 of file remoteDM.cpp.
void __fastcall TdmRemote::PlaceOnTrayExecute (TObject * Sender)
Definition at line 541 of file remoteDM.cpp.
WAPlaybackStatus __fastcall TdmRemote::PlaybackStatus ()
Definition at line 718 of file remoteDM.cpp.
Referenced by TfrmMain::IconHandle(), and SongChangedExecute().
void __fastcall TdmRemote::PlayExecute (TObject * Sender)
Definition at line 131 of file remoteDM.cpp.
void __fastcall TdmRemote::PlayFromStartExecute (TObject * Sender)
Definition at line 256 of file remoteDM.cpp.
void __fastcall TdmRemote::PlaylistDragDrop (int dropIndex, int currentPos)
Definition at line 604 of file remoteDM.cpp.
Referenced by TfrmPlaylist::lstSongsDragDrop().
void __fastcall TdmRemote::PlaylistEndExecute (TObject * Sender)
Definition at line 204 of file remoteDM.cpp.
void __fastcall TdmRemote::PlaylistRefreshCurrentExecute (TObject * Sender)
Definition at line 547 of file remoteDM.cpp.
void __fastcall TdmRemote::PlaylistRefreshExecute (TObject * Sender)
Definition at line 364 of file remoteDM.cpp.
void __fastcall TdmRemote::PlaylistRefreshStatsExecute (TObject * Sender)
Definition at line 405 of file remoteDM.cpp.
void __fastcall TdmRemote::PlaylistStartExecute (TObject * Sender)
Definition at line 197 of file remoteDM.cpp.
void __fastcall TdmRemote::PreviousExecute (TObject * Sender)
Definition at line 151 of file remoteDM.cpp.
void __fastcall TdmRemote::PreviousFadeExecute (TObject * Sender)
Definition at line 329 of file remoteDM.cpp.
void __fastcall TdmRemote::registerForm (TForm * aForm)
Definition at line 786 of file remoteDM.cpp.
Referenced by TfrmCommands::FormCreate(), TfrmPlaylist::FormCreate(), TfrmSettings::FormCreate(), and TfrmMain::FormCreate().
void __fastcall TdmRemote::RepeatExecute (TObject * Sender)
Definition at line 248 of file remoteDM.cpp.
void __fastcall TdmRemote::RestoreOnStartExecute (TObject * Sender)
Definition at line 839 of file remoteDM.cpp.
void __fastcall TdmRemote::SetBalance (int balance)
Definition at line 672 of file remoteDM.cpp.
Referenced by TfrmSettings::tbBalanceChange().
void TdmRemote::setClient (WinampRemote::Client::IWinamp * client_)
void __fastcall TdmRemote::SetSongPosition (int pos, int width)
Definition at line 655 of file remoteDM.cpp.
Referenced by TfrmPlaylist::pbSongPosMouseMove().
void __fastcall TdmRemote::SetVolume (int volume)
Definition at line 666 of file remoteDM.cpp.
Referenced by TfrmSettings::tbVolumeChange().
void __fastcall TdmRemote::SetVolume0Execute (TObject * Sender)
Definition at line 227 of file remoteDM.cpp.
void __fastcall TdmRemote::SetVolume100Execute (TObject * Sender)
Definition at line 234 of file remoteDM.cpp.
void __fastcall TdmRemote::ShowMainFormExecute (TObject * Sender)
Definition at line 552 of file remoteDM.cpp.
void __fastcall TdmRemote::ShuffleExecute (TObject * Sender)
Definition at line 240 of file remoteDM.cpp.
void __fastcall TdmRemote::SongChangedExecute (TObject * Sender)
Definition at line 346 of file remoteDM.cpp.
void __fastcall TdmRemote::SongChangingExecute (TObject * Sender)
Definition at line 337 of file remoteDM.cpp.
void __fastcall TdmRemote::StartExecute (TObject * Sender)
Definition at line 587 of file remoteDM.cpp.
void __fastcall TdmRemote::StopAfterCurrentExecute (TObject * Sender)
Definition at line 222 of file remoteDM.cpp.
void __fastcall TdmRemote::StopExecute (TObject * Sender)
Definition at line 158 of file remoteDM.cpp.
void __fastcall TdmRemote::StopFadeExecute (TObject * Sender)
Definition at line 217 of file remoteDM.cpp.
void __fastcall TdmRemote::unRegisterForm (TForm * aForm)
Definition at line 823 of file remoteDM.cpp.
Referenced by TfrmCommands::FormDestroy(), TfrmSettings::FormDestroy(), TfrmPlaylist::FormDestroy(), and TfrmMain::FormDestroy().
void __fastcall TdmRemote::UpdateBars ()
Definition at line 685 of file remoteDM.cpp.
Referenced by FullExecute(), HalfExecute(), SetVolume0Execute(), SetVolume100Execute(), UpdateValues(), VolumeDownExecute(), VolumeDownMoreExecute(), VolumeUpExecute(), VolumeUpMoreExecute(), and ZeroExecute().
void __fastcall TdmRemote::UpdateValues ()
Definition at line 702 of file remoteDM.cpp.
void __fastcall TdmRemote::UpExecute (TObject * Sender)
Definition at line 593 of file remoteDM.cpp.
void __fastcall TdmRemote::UpMoreExecute (TObject * Sender)
Definition at line 598 of file remoteDM.cpp.
void __fastcall TdmRemote::ViewPlaylistExecute (TObject * Sender)
Definition at line 290 of file remoteDM.cpp.
void __fastcall TdmRemote::ViewToolBarExecute (TObject * Sender)
Definition at line 283 of file remoteDM.cpp.
void __fastcall TdmRemote::ViewVolumeExecute (TObject * Sender)
Definition at line 296 of file remoteDM.cpp.
void __fastcall TdmRemote::VolumeDownExecute (TObject * Sender)
Definition at line 179 of file remoteDM.cpp.
void __fastcall TdmRemote::VolumeDownMoreExecute (TObject * Sender)
Definition at line 191 of file remoteDM.cpp.
void __fastcall TdmRemote::VolumeUpExecute (TObject * Sender)
Definition at line 173 of file remoteDM.cpp.
void __fastcall TdmRemote::VolumeUpMoreExecute (TObject * Sender)
Definition at line 185 of file remoteDM.cpp.
std::string __fastcall TdmRemote::WinampVersionString ()
Definition at line 723 of file remoteDM.cpp.
void __fastcall TdmRemote::ZeroExecute (TObject * Sender)
Definition at line 263 of file remoteDM.cpp.
Member Data Documentation
TAction* TdmRemote::About
Definition at line 59 of file remoteDM.h.
TAction* TdmRemote::AddDirectory
Definition at line 50 of file remoteDM.h.
TAction* TdmRemote::AddPlayIist
Definition at line 49 of file remoteDM.h.
TActionList* TdmRemote::alMain
Definition at line 29 of file remoteDM.h.
TAction* TdmRemote::Autoload
Definition at line 62 of file remoteDM.h.
Referenced by AutoloadExecute(), and TfrmSettings::UpdateBars().
TAction* TdmRemote::Back5
Definition at line 39 of file remoteDM.h.
TAction* TdmRemote::ChangeFade
Definition at line 75 of file remoteDM.h.
Referenced by SongChangedExecute(), and SongChangingExecute().
TAction* TdmRemote::Details
Definition at line 63 of file remoteDM.h.
TAction* TdmRemote::Down
Definition at line 53 of file remoteDM.h.
TAction* TdmRemote::DownMore
Definition at line 55 of file remoteDM.h.
TAction* TdmRemote::End
Definition at line 46 of file remoteDM.h.
TAction* TdmRemote::EQOn
Definition at line 71 of file remoteDM.h.
Referenced by EQOnExecute(), and TfrmSettings::UpdateBars().
TAction* TdmRemote::Exit
Definition at line 31 of file remoteDM.h.
TAction* TdmRemote::Forward5
Definition at line 38 of file remoteDM.h.
TAction* TdmRemote::Full
Definition at line 58 of file remoteDM.h.
TAction* TdmRemote::Half
Definition at line 57 of file remoteDM.h.
TAction* TdmRemote::HideOnStart
Definition at line 73 of file remoteDM.h.
TAction* TdmRemote::LocateServers
Definition at line 61 of file remoteDM.h.
TAction* TdmRemote::NewSong
Definition at line 68 of file remoteDM.h.
Referenced by TfrmPlaylist::lstSongsDblClick().
TAction* TdmRemote::Next
Definition at line 43 of file remoteDM.h.
Referenced by NextFadeExecute().
TAction* TdmRemote::NextFade
Definition at line 64 of file remoteDM.h.
TOpenDialog* TdmRemote::odlgMain
Definition at line 72 of file remoteDM.h.
Referenced by AddPlayIistExecute().
TAction* TdmRemote::Pause
Definition at line 33 of file remoteDM.h.
Referenced by TfrmMain::IconHandle().
TAction* TdmRemote::PlaceOnTray
Definition at line 30 of file remoteDM.h.
TAction* TdmRemote::Play
Definition at line 34 of file remoteDM.h.
Referenced by NewSongExecute(), NextFadeExecute(), PreviousFadeExecute(), and SongChangedExecute().
TAction* TdmRemote::PlayFromStart
Definition at line 48 of file remoteDM.h.
TAction* TdmRemote::PlaylistRefresh
Definition at line 47 of file remoteDM.h.
Referenced by AddPlayIistExecute(), DeletePlayListExecute(), DoDeleteSelected(), DropFiles(), TfrmPlaylist::FormCreate(), TfrmPlaylist::mnuRefreshClick(), and PlaylistDragDrop().
TAction* TdmRemote::PlaylistRefreshCurrent
Definition at line 69 of file remoteDM.h.
TAction* TdmRemote::PlaylistRefreshStats
Definition at line 70 of file remoteDM.h.
Referenced by UpdateValues().
TAction* TdmRemote::Previous
Definition at line 44 of file remoteDM.h.
Referenced by PreviousFadeExecute().
TAction* TdmRemote::PreviousFade
Definition at line 65 of file remoteDM.h.
TAction* TdmRemote::Repeat
Definition at line 42 of file remoteDM.h.
Referenced by RepeatExecute(), and UpdateValues().
TAction* TdmRemote::RestoreOnStart
Definition at line 74 of file remoteDM.h.
TAction* TdmRemote::ShowMainForm
Definition at line 60 of file remoteDM.h.
TAction* TdmRemote::Shuffle
Definition at line 41 of file remoteDM.h.
Referenced by ShuffleExecute(), and UpdateValues().
TAction* TdmRemote::SongChanged
Definition at line 67 of file remoteDM.h.
Referenced by NewSongExecute(), NextExecute(), PlayFromStartExecute(), PlaylistEndExecute(), PlaylistStartExecute(), and PreviousExecute().
TAction* TdmRemote::SongChanging
Definition at line 66 of file remoteDM.h.
Referenced by NewSongExecute(), NextExecute(), PlayFromStartExecute(), PlaylistEndExecute(), PlaylistStartExecute(), and PreviousExecute().
TAction* TdmRemote::Start
Definition at line 45 of file remoteDM.h.
TAction* TdmRemote::Stop
Definition at line 35 of file remoteDM.h.
TAction* TdmRemote::StopAfterCurrent
Definition at line 37 of file remoteDM.h.
TAction* TdmRemote::StopFade
Definition at line 36 of file remoteDM.h.
Referenced by NextFadeExecute(), PreviousFadeExecute(), and SongChangingExecute().
TAction* TdmRemote::Up
Definition at line 52 of file remoteDM.h.
TAction* TdmRemote::UpMore
Definition at line 54 of file remoteDM.h.
TAction* TdmRemote::ViewPlaylist
Definition at line 40 of file remoteDM.h.
Referenced by ViewPlaylistExecute().
TAction* TdmRemote::ViewToolBar
Definition at line 32 of file remoteDM.h.
Referenced by ViewToolBarExecute().
TAction* TdmRemote::ViewVolume
Definition at line 51 of file remoteDM.h.
Referenced by ViewVolumeExecute().
TAction* TdmRemote::Zero
Definition at line 56 of file remoteDM.h.
The documentation for this class was generated from the following files:
remoteDM.h
remoteDM.cpp