The Winamp Remote Control suite: WinampRemote::Client::WinampClientBase Class Reference
WinampRemote::Client::WinampClientBase Class Reference
#include <WinampClientBase.h>
Public Member Functions
WinampClientBase ()
virtual ~WinampClientBase ()
virtual int winampVersion (void) const
virtual void sendString ()
virtual void nextSong (void)
virtual void previousSong (void)
virtual void playSong (void)
virtual void stopSong (void)
virtual void pause (void)
virtual WAPlaybackStatus getPlaybackStatus (void) const
virtual string getPlayListItem (int index, bool title=true) const
virtual int getCurrentPlayPosition (void) const
virtual int getPlaylistLength (void) const
virtual string getCurrentPlayListItem (int &index, bool title=true) const
virtual vector< string > getPlayList (bool title=true) const
virtual void setPlayList (const vector< string > &playlist)
virtual void insertPlayList (const vector< string > &playlist, int position)
virtual void playlistStart ()
virtual void playlistEnd ()
virtual void setPlaylistIndex (int index)
virtual void startPlaylist (void)
virtual void deletePlaylist (void)
virtual void stopWithFade (void)
virtual void stopAfterCurrent (void)
virtual void setTime (int time)
virtual int getTime () const
virtual void forward5 (void)
virtual void back5 (void)
virtual void volumeUp (void)
virtual void volumeDown (void)
virtual void setVolume (int volume)
virtual int getVolume () const
virtual void setPanning (int panning)
virtual int getPanning () const
virtual void toggleShuffle (void)
virtual int getShuffle (void) const
virtual void setShuffle (bool shuffle)
virtual void toggleRepeat (void)
virtual int getRepeat (void) const
virtual void setRepeat (bool repeat)
virtual void toggleEQOn (void)
virtual int getEQOn (void) const
virtual void setEQOn (bool value)
virtual void toggleAutoload (void)
virtual int getAutoload (void) const
virtual void setAutoload (bool value)
virtual int getEQData (int eqindex) const
void setEQData (int eqindex, byte eqvalue)
virtual void getTimes (int &songLength, int &songPos) const
virtual std::string getStringList (WinampCommand Command) const
virtual void setStringList (const std::string &list, WinampCommand Command)
Public Member Functions inherited from WinampRemote::Client::IWinamp
virtual ~IWinamp ()
Detailed Description
A concrete implementation of the a IWinamp client for console use
Definition at line 21 of file WinampClientBase.h.
Constructor & Destructor Documentation
WinampRemote::Client::WinampClientBase::WinampClientBase ()
no - params constructor
Definition at line 33 of file WinampClientBase.cpp.
virtual WinampRemote::Client::WinampClientBase::~WinampClientBase () inline virtual
destructor
Definition at line 34 of file WinampClientBase.h.
Member Function Documentation
void WinampRemote::Client::WinampClientBase::back5 (void) virtual
rewinds the position in the playlist by 5
Implements WinampRemote::Client::IWinamp.
Definition at line 210 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::deletePlaylist (void) virtual
deletes the playlist
Implements WinampRemote::Client::IWinamp.
Definition at line 180 of file WinampClientBase.cpp.
Referenced by setPlayList(), and TEST_CASE().
void WinampRemote::Client::WinampClientBase::forward5 (void) virtual
advances the position in the playlist by 5
Implements WinampRemote::Client::IWinamp.
Definition at line 205 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
int WinampRemote::Client::WinampClientBase::getAutoload (void) const virtual
returns the autoload option
Implements WinampRemote::Client::IWinamp.
Definition at line 302 of file WinampClientBase.cpp.
Referenced by TEST_CASE(), and toggleAutoload().
string WinampRemote::Client::WinampClientBase::getCurrentPlayListItem (int & index, bool title = true) const virtual
returns the current playlist item and current index, either title or filename
Parameters:
index
title
Returns:
Implements WinampRemote::Client::IWinamp.
Definition at line 98 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
int WinampRemote::Client::WinampClientBase::getCurrentPlayPosition (void) const virtual
returns the current playlist position
Returns:
the index
Implements WinampRemote::Client::IWinamp.
Definition at line 88 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
int WinampRemote::Client::WinampClientBase::getEQData (int eqindex) const virtual
returns the eq data
Implements WinampRemote::Client::IWinamp.
Definition at line 312 of file WinampClientBase.cpp.
Referenced by getAutoload(), getEQOn(), setEQData(), and TEST_CASE().
int WinampRemote::Client::WinampClientBase::getEQOn (void) const virtual
returns the EQ On option
Implements WinampRemote::Client::IWinamp.
Definition at line 287 of file WinampClientBase.cpp.
Referenced by TEST_CASE(), and toggleEQOn().
int WinampRemote::Client::WinampClientBase::getPanning () const virtual
returns the panning
Implements WinampRemote::Client::IWinamp.
Definition at line 240 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
WAPlaybackStatus WinampRemote::Client::WinampClientBase::getPlaybackStatus (void) const virtual
query playback status
Returns:
the playback status
Implements WinampRemote::Client::IWinamp.
Definition at line 73 of file WinampClientBase.cpp.
Referenced by main(), and TEST_CASE().
vector< string > WinampRemote::Client::WinampClientBase::getPlayList (bool title = true) const virtual
returns the playlist
Returns:
the playlist
Implements WinampRemote::Client::IWinamp.
Definition at line 105 of file WinampClientBase.cpp.
Referenced by insertPlayList(), main(), and TEST_CASE().
string WinampRemote::Client::WinampClientBase::getPlayListItem (int index, bool title = true) const virtual
returns the playlist item, either title or filename
Returns:
the playlist item property
Implements WinampRemote::Client::IWinamp.
Definition at line 79 of file WinampClientBase.cpp.
Referenced by getCurrentPlayListItem(), and TEST_CASE().
int WinampRemote::Client::WinampClientBase::getPlaylistLength (void) const virtual
returns the current playlist length
Returns:
the length
Implements WinampRemote::Client::IWinamp.
Definition at line 93 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
int WinampRemote::Client::WinampClientBase::getRepeat (void) const virtual
returns the repeat option
Implements WinampRemote::Client::IWinamp.
Definition at line 268 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
int WinampRemote::Client::WinampClientBase::getShuffle (void) const virtual
returns the shuffle option
Implements WinampRemote::Client::IWinamp.
Definition at line 251 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
std::string WinampRemote::Client::WinampClientBase::getStringList (WinampCommand Command) const virtual
returns the string list run over all the playlist for the given StringResult command
Parameters:
Command
Returns:
the returns in TStrings format
Implements WinampRemote::Client::IWinamp.
Definition at line 334 of file WinampClientBase.cpp.
Referenced by getPlayList().
int WinampRemote::Client::WinampClientBase::getTime () const virtual
gets the current song time position
Implements WinampRemote::Client::IWinamp.
Definition at line 200 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::getTimes (int & songLength, int & songPos) const virtual
returns the current song times for length and position in seconds and milliseconds respectively
Parameters:
songLength
songPos
Implements WinampRemote::Client::IWinamp.
Definition at line 323 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
int WinampRemote::Client::WinampClientBase::getVolume () const virtual
returns the volume
Implements WinampRemote::Client::IWinamp.
Definition at line 230 of file WinampClientBase.cpp.
Referenced by TEST_CASE(), volumeDown(), and volumeUp().
void WinampRemote::Client::WinampClientBase::insertPlayList (const vector< string > & playlist, int position) virtual
inserts the passed playlist into the existing playlist, beginning from the passed position
Parameters:
playlist
position
Implements WinampRemote::Client::IWinamp.
Definition at line 145 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::nextSong (void) virtual
move to next song
Implements WinampRemote::Client::IWinamp.
Definition at line 48 of file WinampClientBase.cpp.
Referenced by main(), and TEST_CASE().
void WinampRemote::Client::WinampClientBase::pause (void) virtual
pause playing
Implements WinampRemote::Client::IWinamp.
Definition at line 68 of file WinampClientBase.cpp.
Referenced by main(), and TEST_CASE().
void WinampRemote::Client::WinampClientBase::playlistEnd () virtual
go to end of playlist
Implements WinampRemote::Client::IWinamp.
Definition at line 165 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::playlistStart () virtual
go to start of playList
Implements WinampRemote::Client::IWinamp.
Definition at line 160 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::playSong (void) virtual
play the current item in playlist
Implements WinampRemote::Client::IWinamp.
Definition at line 58 of file WinampClientBase.cpp.
Referenced by main(), and TEST_CASE().
void WinampRemote::Client::WinampClientBase::previousSong (void) virtual
move to prior song
Implements WinampRemote::Client::IWinamp.
Definition at line 53 of file WinampClientBase.cpp.
Referenced by main(), and TEST_CASE().
void WinampRemote::Client::WinampClientBase::sendString () virtual
send a string to the server
Implements WinampRemote::Client::IWinamp.
Definition at line 43 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::setAutoload (bool value) virtual
sets the autoload options
Parameters:
value
Implements WinampRemote::Client::IWinamp.
Definition at line 307 of file WinampClientBase.cpp.
Referenced by TEST_CASE(), and toggleAutoload().
void WinampRemote::Client::WinampClientBase::setEQData (int eqindex, byte eqvalue) virtual
sets the eq data
Implements WinampRemote::Client::IWinamp.
Definition at line 317 of file WinampClientBase.cpp.
Referenced by setAutoload(), setEQOn(), and TEST_CASE().
void WinampRemote::Client::WinampClientBase::setEQOn (bool value) virtual
sets the EQ On option
Parameters:
value
Implements WinampRemote::Client::IWinamp.
Definition at line 292 of file WinampClientBase.cpp.
Referenced by TEST_CASE(), and toggleEQOn().
void WinampRemote::Client::WinampClientBase::setPanning (int panning) virtual
sets the panning
Parameters:
panning
Implements WinampRemote::Client::IWinamp.
Definition at line 235 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::setPlayList (const vector< string > & playlist) virtual
sets the playlist on the server
Parameters:
playlist
Implements WinampRemote::Client::IWinamp.
Definition at line 128 of file WinampClientBase.cpp.
Referenced by insertPlayList(), and TEST_CASE().
void WinampRemote::Client::WinampClientBase::setPlaylistIndex (int index) virtual
sets the current playlist index
Parameters:
index
Implements WinampRemote::Client::IWinamp.
Definition at line 170 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::setRepeat (bool repeat) virtual
sets the repeat option
Implements WinampRemote::Client::IWinamp.
Definition at line 276 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::setShuffle (bool shuffle) virtual
set the shuffle option
Parameters:
shuffle
Implements WinampRemote::Client::IWinamp.
Definition at line 256 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::setStringList (const std::string & list, WinampCommand Command) virtual
apply the passed list of string values in TStrings format with the passed command
Parameters:
list
Command
Implements WinampRemote::Client::IWinamp.
Definition at line 352 of file WinampClientBase.cpp.
Referenced by setPlayList().
void WinampRemote::Client::WinampClientBase::setTime (int time) virtual
sets the current song time position
Parameters:
time
Implements WinampRemote::Client::IWinamp.
Definition at line 195 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::setVolume (int volume) virtual
sets the volume
Parameters:
volume
Implements WinampRemote::Client::IWinamp.
Definition at line 225 of file WinampClientBase.cpp.
Referenced by TEST_CASE(), volumeDown(), and volumeUp().
void WinampRemote::Client::WinampClientBase::startPlaylist (void) virtual
sets current position to the start of the playlist
Implements WinampRemote::Client::IWinamp.
Definition at line 175 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::stopAfterCurrent (void) virtual
stops playback after the current
Implements WinampRemote::Client::IWinamp.
Definition at line 190 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::stopSong (void) virtual
stop playing
Implements WinampRemote::Client::IWinamp.
Definition at line 63 of file WinampClientBase.cpp.
Referenced by main(), and TEST_CASE().
void WinampRemote::Client::WinampClientBase::stopWithFade (void) virtual
performs a stop with fade
Implements WinampRemote::Client::IWinamp.
Definition at line 185 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::toggleAutoload (void) virtual
toggles the autoload option
Implements WinampRemote::Client::IWinamp.
Definition at line 297 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::toggleEQOn (void) virtual
toggles the EQ On option
Implements WinampRemote::Client::IWinamp.
Definition at line 282 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::toggleRepeat (void) virtual
toggles the repeat option
Implements WinampRemote::Client::IWinamp.
Definition at line 261 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::toggleShuffle (void) virtual
toggles the shuffle option
Implements WinampRemote::Client::IWinamp.
Definition at line 246 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::volumeDown (void) virtual
decrements volume
Implements WinampRemote::Client::IWinamp.
Definition at line 220 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
void WinampRemote::Client::WinampClientBase::volumeUp (void) virtual
increments volume
Implements WinampRemote::Client::IWinamp.
Definition at line 215 of file WinampClientBase.cpp.
Referenced by TEST_CASE().
int WinampRemote::Client::WinampClientBase::winampVersion (void) const virtual
return the hosting winamp version
Returns:
the winamp version number
Implements WinampRemote::Client::IWinamp.
Definition at line 38 of file WinampClientBase.cpp.
Referenced by main(), TEST_CASE(), and ServerTester::testServer().
The documentation for this class was generated from the following files:
WinampClientBase.h
WinampClientBase.cpp