The Winamp Remote Control suite: AboutGLDisplay Class Reference
AboutGLDisplay Class Reference
#include <AboutGLDisplay.h>
Classes
struct GLOptions
Public Member Functions
GLOptions & gloptions ()
void setProjection () const
void setClientArea (int clientWidth_, int clientHeight_)
void redraw () const
void startMotion (DWORD time, int button, int x, int y)
void stopMotion (DWORD time, int button, int x, int y)
void trackMotion (DWORD time, int x, int y)
AboutGLDisplay (HDC hDC_, int clientWidth_, int clientHeight_)
virtual ~AboutGLDisplay ()
Public Attributes
GLfloat xOffset
GLfloat yOffset
Static Public Attributes
static const GLfloat X_OFFSET_STEP = 5
static const GLfloat Y_OFFSET_STEP = 5
Detailed Description
Definition at line 17 of file AboutGLDisplay.h.
Constructor & Destructor Documentation
AboutGLDisplay::AboutGLDisplay (HDC hDC_, int clientWidth_, int clientHeight_)
constructs the About GL display class on a given DC, with client area
Parameters:
hDC_
clientWidth_
clientHeight_
Definition at line 45 of file AboutGLDisplay.cpp.
AboutGLDisplay::~AboutGLDisplay () virtual
Definition at line 67 of file AboutGLDisplay.cpp.
Member Function Documentation
AboutGLDisplay::GLOptions & AboutGLDisplay::gloptions ()
returns the GL options in force for the next repaint
Returns:
reference to the options
Definition at line 76 of file AboutGLDisplay.cpp.
Referenced by TfrmAbout::FormKeyPress().
void AboutGLDisplay::redraw (void) const
draws the current scene
Definition at line 652 of file AboutGLDisplay.cpp.
void AboutGLDisplay::setClientArea (int clientWidth_, int clientHeight_)
sets the client area - clients use when this has changed
Parameters:
clientWidth_
clientHeight_
Definition at line 81 of file AboutGLDisplay.cpp.
void AboutGLDisplay::setProjection (void) const
re-asserts the projection - use when the size or projection desired is updated
Definition at line 566 of file AboutGLDisplay.cpp.
void AboutGLDisplay::startMotion (DWORD time, int button, int x, int y)
starts a mouse move
Parameters:
time
button
x
y
Definition at line 791 of file AboutGLDisplay.cpp.
Referenced by TfrmAbout::FormMouseDown().
void AboutGLDisplay::stopMotion (DWORD time, int button, int x, int y)
ends a mouse move
Parameters:
time
button
x
y
Definition at line 808 of file AboutGLDisplay.cpp.
Referenced by TfrmAbout::FormMouseUp().
void AboutGLDisplay::trackMotion (DWORD time, int x, int y)
invoke for mouse tracking
Parameters:
time
x
y
Definition at line 828 of file AboutGLDisplay.cpp.
Referenced by TfrmAbout::FormMouseMove().
Member Data Documentation
const GLfloat AboutGLDisplay::X_OFFSET_STEP = 5 static
X offset step for adjustment
Definition at line 229 of file AboutGLDisplay.h.
Referenced by TfrmAbout::FormKeyPress().
GLfloat AboutGLDisplay::xOffset
X offset for the viewport
Definition at line 221 of file AboutGLDisplay.h.
Referenced by TfrmAbout::FormKeyPress(), and redraw().
const GLfloat AboutGLDisplay::Y_OFFSET_STEP = 5 static
Y offset step for adjustment
Definition at line 233 of file AboutGLDisplay.h.
Referenced by TfrmAbout::FormKeyPress().
GLfloat AboutGLDisplay::yOffset
Y offset for the viewport
Definition at line 225 of file AboutGLDisplay.h.
Referenced by TfrmAbout::FormKeyPress(), and redraw().
The documentation for this class was generated from the following files:
AboutGLDisplay.h
AboutGLDisplay.cpp