The Winamp Remote Control suite: WinampRemote::Client::IWinamp Class Reference
WinampRemote::Client::IWinamp Class Reference
#include <IWinamp.h>
Public Member Functions
virtual ~IWinamp ()
virtual int winampVersion (void) const =0
virtual void sendString ()=0
virtual void nextSong (void)=0
virtual void previousSong (void)=0
virtual void playSong (void)=0
virtual void stopSong (void)=0
virtual void pause (void)=0
virtual WAPlaybackStatus getPlaybackStatus (void) const =0
virtual string getPlayListItem (int index, bool title=true) const =0
virtual int getCurrentPlayPosition (void) const =0
virtual int getPlaylistLength (void) const =0
virtual string getCurrentPlayListItem (int &index, bool title=true) const =0
virtual vector< string > getPlayList (bool title=true) const =0
virtual void setPlayList (const vector< string > &playlist)=0
virtual void insertPlayList (const vector< string > &playlist, int position)=0
virtual void playlistStart ()=0
virtual void playlistEnd ()=0
virtual void setPlaylistIndex (int index)=0
virtual void startPlaylist (void)=0
virtual void deletePlaylist (void)=0
virtual void stopWithFade (void)=0
virtual void stopAfterCurrent (void)=0
virtual void setTime (int time)=0
virtual int getTime () const =0
virtual void forward5 (void)=0
virtual void back5 (void)=0
virtual void volumeUp (void)=0
virtual void volumeDown (void)=0
virtual void setVolume (int volume)=0
virtual int getVolume () const =0
virtual void setPanning (int panning)=0
virtual int getPanning () const =0
virtual void toggleShuffle (void)=0
virtual int getShuffle (void) const =0
virtual void setShuffle (bool shuffle)=0
virtual void toggleRepeat (void)=0
virtual int getRepeat (void) const =0
virtual void setRepeat (bool repeat)=0
virtual void toggleEQOn (void)=0
virtual int getEQOn (void) const =0
virtual void setEQOn (bool value)=0
virtual void toggleAutoload (void)=0
virtual int getAutoload (void) const =0
virtual void setAutoload (bool value)=0
virtual int getEQData (int eqindex) const =0
virtual void setEQData (int eqindex, byte eqvalue)=0
virtual void getTimes (int &songLength, int &songPos) const =0
virtual std::string getStringList (WinampCommand Command) const =0
virtual void setStringList (const std::string &list, WinampCommand Command)=0
Detailed Description
Definition at line 24 of file IWinamp.h.
Constructor & Destructor Documentation
virtual WinampRemote::Client::IWinamp::~IWinamp () inline virtual
Definition at line 30 of file IWinamp.h.
Member Function Documentation
virtual void WinampRemote::Client::IWinamp::back5 (void) pure virtual
rewinds the position in the playlist by 5
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::Back5Execute().
virtual void WinampRemote::Client::IWinamp::deletePlaylist (void) pure virtual
deletes the playlist
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::DeletePlayListExecute().
virtual void WinampRemote::Client::IWinamp::forward5 (void) pure virtual
advances the position in the playlist by 5
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::Forward5Execute().
virtual int WinampRemote::Client::IWinamp::getAutoload (void) const pure virtual
returns the autoload option
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::AutoloadExecute(), and TdmRemote::UpdateBars().
virtual string WinampRemote::Client::IWinamp::getCurrentPlayListItem (int & index, bool title = true) const pure virtual
returns the current playlist item and current index, either title or filename
Parameters:
index
title
Returns:
Implemented in WinampRemote::Client::WinampClientBase.
virtual int WinampRemote::Client::IWinamp::getCurrentPlayPosition (void) const pure virtual
returns the current playlist position
Returns:
the index
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::CurrentSong(), TdmRemote::GetPlaylistState(), and TdmRemote::PlaylistRefreshExecute().
virtual int WinampRemote::Client::IWinamp::getEQData (int eqindex) const pure virtual
returns the eq data
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::UpdateBars().
virtual int WinampRemote::Client::IWinamp::getEQOn (void) const pure virtual
returns the EQ On option
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::EQOnExecute(), and TdmRemote::UpdateBars().
virtual int WinampRemote::Client::IWinamp::getPanning () const pure virtual
returns the panning
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::UpdateValues().
virtual WAPlaybackStatus WinampRemote::Client::IWinamp::getPlaybackStatus (void) const pure virtual
query playback status
Returns:
the playback status
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::PlaybackStatus().
virtual vector<string> WinampRemote::Client::IWinamp::getPlayList (bool title = true) const pure virtual
returns the playlist
Returns:
the playlist
Implemented in WinampRemote::Client::WinampClientBase.
virtual string WinampRemote::Client::IWinamp::getPlayListItem (int index, bool title = true) const pure virtual
returns the playlist item, either title or filename
Returns:
the playlist item property
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::CurrentSong(), and TdmRemote::PlaylistDragDrop().
virtual int WinampRemote::Client::IWinamp::getPlaylistLength (void) const pure virtual
returns the current playlist length
Returns:
the length
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::GetPlaylistState(), and TdmRemote::PlaylistRefreshExecute().
virtual int WinampRemote::Client::IWinamp::getRepeat (void) const pure virtual
returns the repeat option
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::RepeatExecute(), and TdmRemote::UpdateValues().
virtual int WinampRemote::Client::IWinamp::getShuffle (void) const pure virtual
returns the shuffle option
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::ShuffleExecute(), and TdmRemote::UpdateValues().
virtual std::string WinampRemote::Client::IWinamp::getStringList (WinampCommand Command) const pure virtual
returns the string list run over all the playlist for the given StringResult command
Parameters:
Command
Returns:
the returns in TStrings format
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::DoDeleteSelected(), and TdmRemote::PlaylistRefreshExecute().
virtual int WinampRemote::Client::IWinamp::getTime () const pure virtual
gets the current song time position
Implemented in WinampRemote::Client::WinampClientBase.
virtual void WinampRemote::Client::IWinamp::getTimes (int & songLength, int & songPos) const pure virtual
returns the current song times for length and position in seconds and milliseconds respectively
Parameters:
songLength
songPos
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::PlaylistRefreshStatsExecute(), and TdmRemote::SetSongPosition().
virtual int WinampRemote::Client::IWinamp::getVolume () const pure virtual
returns the volume
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::UpdateValues(), TdmRemote::VolumeDownMoreExecute(), and TdmRemote::VolumeUpMoreExecute().
virtual void WinampRemote::Client::IWinamp::insertPlayList (const vector< string > & playlist, int position) pure virtual
inserts the passed playlist into the existing playlist, beginning from the passed position
Parameters:
playlist
position
Implemented in WinampRemote::Client::WinampClientBase.
virtual void WinampRemote::Client::IWinamp::nextSong (void) pure virtual
move to next song
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::NextExecute().
virtual void WinampRemote::Client::IWinamp::pause (void) pure virtual
pause playing
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::PauseExecute().
virtual void WinampRemote::Client::IWinamp::playlistEnd () pure virtual
go to end of playlist
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::PlaylistEndExecute().
virtual void WinampRemote::Client::IWinamp::playlistStart () pure virtual
go to start of playList
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::PlayFromStartExecute().
virtual void WinampRemote::Client::IWinamp::playSong (void) pure virtual
play the current item in playlist
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::PlayExecute().
virtual void WinampRemote::Client::IWinamp::previousSong (void) pure virtual
move to prior song
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::PreviousExecute().
virtual void WinampRemote::Client::IWinamp::sendString () pure virtual
send a string to the server
Implemented in WinampRemote::Client::WinampClientBase.
virtual void WinampRemote::Client::IWinamp::setAutoload (bool value) pure virtual
sets the autoload options
Parameters:
value
Implemented in WinampRemote::Client::WinampClientBase.
virtual void WinampRemote::Client::IWinamp::setEQData (int eqindex, byte eqvalue) pure virtual
sets the eq data
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::BarChange().
virtual void WinampRemote::Client::IWinamp::setEQOn (bool value) pure virtual
sets the EQ On option
Parameters:
value
Implemented in WinampRemote::Client::WinampClientBase.
virtual void WinampRemote::Client::IWinamp::setPanning (int panning) pure virtual
sets the panning
Parameters:
panning
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::SetBalance().
virtual void WinampRemote::Client::IWinamp::setPlayList (const vector< string > & playlist) pure virtual
sets the playlist on the server
Parameters:
playlist
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::DoAddFiles().
virtual void WinampRemote::Client::IWinamp::setPlaylistIndex (int index) pure virtual
sets the current playlist index
Parameters:
index
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::DoAddFiles(), TdmRemote::DoDeleteSelected(), TdmRemote::DropFiles(), TdmRemote::NewSongExecute(), and TdmRemote::PlaylistDragDrop().
virtual void WinampRemote::Client::IWinamp::setRepeat (bool repeat) pure virtual
sets the repeat option
Implemented in WinampRemote::Client::WinampClientBase.
virtual void WinampRemote::Client::IWinamp::setShuffle (bool shuffle) pure virtual
set the shuffle option
Parameters:
shuffle
Implemented in WinampRemote::Client::WinampClientBase.
virtual void WinampRemote::Client::IWinamp::setStringList (const std::string & list, WinampCommand Command) pure virtual
apply the passed list of string values in TStrings format with the passed command
Parameters:
list
Command
Implemented in WinampRemote::Client::WinampClientBase.
virtual void WinampRemote::Client::IWinamp::setTime (int time) pure virtual
sets the current song time position
Parameters:
time
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::SetSongPosition().
virtual void WinampRemote::Client::IWinamp::setVolume (int volume) pure virtual
sets the volume
Parameters:
volume
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::FullExecute(), TdmRemote::HalfExecute(), TdmRemote::SetVolume(), TdmRemote::SetVolume0Execute(), TdmRemote::SetVolume100Execute(), TdmRemote::VolumeDownMoreExecute(), TdmRemote::VolumeUpMoreExecute(), and TdmRemote::ZeroExecute().
virtual void WinampRemote::Client::IWinamp::startPlaylist (void) pure virtual
sets current position to the start of the playlist
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::PlaylistStartExecute().
virtual void WinampRemote::Client::IWinamp::stopAfterCurrent (void) pure virtual
stops playback after the current
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::StopAfterCurrentExecute().
virtual void WinampRemote::Client::IWinamp::stopSong (void) pure virtual
stop playing
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::StopExecute().
virtual void WinampRemote::Client::IWinamp::stopWithFade (void) pure virtual
performs a stop with fade
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::StopFadeExecute().
virtual void WinampRemote::Client::IWinamp::toggleAutoload (void) pure virtual
toggles the autoload option
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::AutoloadExecute().
virtual void WinampRemote::Client::IWinamp::toggleEQOn (void) pure virtual
toggles the EQ On option
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::EQOnExecute().
virtual void WinampRemote::Client::IWinamp::toggleRepeat (void) pure virtual
toggles the repeat option
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::RepeatExecute().
virtual void WinampRemote::Client::IWinamp::toggleShuffle (void) pure virtual
toggles the shuffle option
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::ShuffleExecute().
virtual void WinampRemote::Client::IWinamp::volumeDown (void) pure virtual
decrements volume
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::VolumeDownExecute().
virtual void WinampRemote::Client::IWinamp::volumeUp (void) pure virtual
increments volume
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::VolumeUpExecute().
virtual int WinampRemote::Client::IWinamp::winampVersion (void) const pure virtual
return the hosting winamp version
Returns:
the winamp version number
Implemented in WinampRemote::Client::WinampClientBase.
Referenced by TdmRemote::RepeatExecute(), TdmRemote::ShuffleExecute(), TdmRemote::UpdateValues(), and TdmRemote::WinampVersionString().
The documentation for this class was generated from the following file:
IWinamp.h