//---------------------------------------------------------------------------
#ifndef RPCFuncsUH
#define RPCFuncsUH
//---------------------------------------------------------------------------

#include <rpc.h>

#include "sysutils.hpp"

#include "winampinterface.h"    // header file generated by MIDL compiler


extern "C"
{
/* this binds to the interface before the RPC call*/
void __stdcall Bind(const char * NetworkAddress, const char * EndPoint);
void __stdcall UnBind(void);

void __stdcall SendString(char * pszString);
void __stdcall ExecuteMessage(char * pszString, int command);
void __stdcall ExecuteStringMessage(char * pszString, char * pszParam, int command);
int __stdcall StringResult(char pszString[WA_RETURN_STRING_SIZE], int command, int data);
int __stdcall IntegerResult(char * pszString, int command, int data);
void __stdcall Shutdown(void);

void __stdcall SetStringList(char * pszString, void * Buffer, int Size, int Command);
void __stdcall GetStringList(char * pszString, void ** Buffer, int& Size, int Command);
void _stdcall GetStringDataList(char * pszString, void ** Buffer, int& Size,
                                int stringcommand, int datacommand, int datadata);


// provide some exception safe versions

int __stdcall SafeSendString(char * pszString);
int __stdcall SafeExecuteMessage(char * pszString, int command);
int __stdcall SafeExecuteStringMessage(char * pszString, char * pszParam, int command);
int __stdcall SafeStringResult(char * pszString, int command, int data, int * Result);
int __stdcall SafeIntegerResult(char * pszString, int command, int data, int * Result);


}

// need to declare these somewhere

void  __RPC_FAR * __RPC_USER midl_user_allocate(size_t len);
void __RPC_USER midl_user_free(void __RPC_FAR * ptr);


#endif
