
#ifndef RPCFuncsUH
#define RPCFuncsUH

#include "winampinterface.h"    // for WA_RETURN_STRING_SIZE in header generated by MIDL


extern "C"
{

void __stdcall SendString(char * pszString);
void __stdcall ExecuteMessage(char * pszString, int command);
void __stdcall ExecuteStringMessage(char * pszString, char * pszParam, int command);
int __stdcall StringResult(char pszString[WA_RETURN_STRING_SIZE], int command, int data);
int __stdcall IntegerResult(char * pszString, int command, int data);
void __stdcall Shutdown(void);

void __stdcall SetStringList(char * pszString, void * Buffer, int Size, int Command);
void __stdcall GetStringList(char * pszString, void ** Buffer, int& Size, int Command);
void __stdcall GetStringDataList(char * pszString, void ** Buffer, int& Size,
                                int stringcommand, int datacommand, int datadata);


// provide some exception safe versions

int __stdcall SafeSendString(char * pszString);
int __stdcall SafeExecuteMessage(char * pszString, int command);
int __stdcall SafeExecuteStringMessage(char * pszString, char * pszParam, int command);
int __stdcall SafeStringResult(char * pszString, int command, int data, int * Result);
int __stdcall SafeIntegerResult(char * pszString, int command, int data, int * Result);


}

#endif
