//---------------------------------------------------------------------------
#ifndef rpcthreadDLLH
#define rpcthreadDLLH
//---------------------------------------------------------------------------
#include <Classes.hpp>
//---------------------------------------------------------------------------


// problem with definition of __try - this gets round out with not problems
#define __try try
#include "winampinterface.h"    // header file generated by MIDL compiler
#include "ServerDLLF.h"         // WAExecutionStatus

// bring the Winamp interfaces
#include "WinampServerImpl.h"



class TRPCServerDLLThread : public TThread
{
protected:
    void __fastcall Execute();
public:
    __fastcall TRPCServerDLLThread(bool CreateSuspended);
    AnsiString Endpoint;
    static ICallObserver& CallObserver;


};


extern TRPCServerDLLThread *serverThread;


  void __fastcall MainMessage(char * msgString);
  void __fastcall MainStatus(WAExecutionStatus Status);
  void __fastcall MainIdent(char * msgString);


//---------------------------------------------------------------------------
#endif
